website/theme.config.tsx
When I try edit page link on docs doesn't work.
=> fix(website): edit page github url

website/pages/docs/getting-started/astro.mdx
astro extension was missed here in https://panda-css.com/docs/getting-started/astro#configure-the-content
=> docs: fix missing astro extension

website/src/components/sections/works-everywhere.tsx, website/theme/icons.tsx
Replace "StoryBook" with "Storybook" everywhere.
=> docs: fix storybook typo

website/pages/docs/concepts/responsive-design.md
I think Panda uses was the intention here. Otherwise, it should be we use and leverage (without an s).
=> feat(docs): fix grammer

website/pages/docs/concepts/cascade-layers.md
Looks to me like there was originally only 3 layers, but it grew to 5?
=> fix(docs): Change 3 to 5 layers in cascade-layers.md page

website/pages/docs/concepts/style-props.mdx
Link to `patterns` in https://panda-css.com/docs/concepts/style-props goes to 404. Replaced with the path that is believed to be the correct.
=> fix broken link

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation_request.yml, .github/pull_request_template.md, website/pages/docs/concepts/recipes.md
=> docs: fix styled typo

website/pages/docs/references/cli.md
> config references in cli docs return a 404 example: https://panda-css.com/docs/references/panda-config#outdir
> config references in cli docs will link to the correct url example: https://panda-css.com/docs/references/config#outdir
No
=> feat(docs): fix config's url

packages/generator/src/engines/pattern.ts
Closes https://github.com/chakra-ui/panda/issues/782
> Allows pattern.properties to be optional
> `panda codegen` errors if a pattern doesn't have a properties object
> `panda codegen` works as expected when a pattern doesn't have a properties object 
No
=> Make pattern.properties optional

extension/vscode/package.json
fixes this, I set it to the same version as [astro](https://github.com/withastro/language-tools/blob/6057e81e758ffab1dee2a27082934ae4480d21f0/packages/vscode/package.json#L32) extension
=> fix(vscode): engines version

website/pages/docs/customization/theme.mdx
Removes `value` key from `breakpoints` in theme config
Docs suggest a `value` key for extending `breakpoints`
`value` key is not used for `breakpoints` 
No
=> Remove 'value' key from breakpoints

website/pages/docs/customization/presets.md
No GitHub issue
In current documentation, theme object passed to `definePreset` is not wrapped by `theme` key. It should be wrapped as shown in example below from `preset-panda`
https://github.com/chakra-ui/panda/blob/main/packages/preset-panda/src/index.ts#L10
N/A
N/A
No
=> docs: preset code examples

.changeset/popular-foxes-deny.md, packages/parser/__tests__/svelte.test.ts, packages/parser/package.json, packages/parser/src/svelte-to-tsx.ts, pnpm-lock.yaml
Closes https://github.com/chakra-ui/panda/issues/813
Fix svelte parsing 
- `<script context="module">` content would not be extracted properly
- Typescript usage in a `<script>` would make the `svelte.parse(code)` crash
- using multiple <script> wasn't working properly either
fixed
no
implementation-wise, I removed the `svelte.parse` cause we can't use `svelte-preprocess` either because of its async-ness
surprisingly it seems ts-morph is parsing just fine in svelte-specific syntax such as `{#if xxx}` `{:catch}` etc, so we just remove the `<script xxx>` & `<style>` tags with regexes
=> fix(parser): svelte with TS / script context / multiple script

.changeset/famous-hotels-flash.md, packages/extractor/__tests__/extract.test.ts, packages/extractor/src/maybe-box-node.ts
Closes #801
`@pandacss/extractor` didnt handle operation tokens. This means that values such as `1 / 2`, `3*5`, `2 **4`, `8- 1` will now properly be extracted
no
=> fix(extractor): handle operation tokens

website/src/nextra/sidebar/sidebar-container.tsx
Closes #830
This PR is for #830 .
The sidebar on the document page is always open on mobile when prefers-reduced-motion is available.
(The sidebar covers a whole screen.)
The sidebar on the document page works fine on mobile when prefers-reduced-motion is available.
No
https://github.com/chakra-ui/panda/assets/10266230/59102d67-d89f-41cb-896a-a0840e4419ff
I'm not sure this PR is the best way to fix #830 . So please check it. And close it if you don't need it.
Thanks.
=> website:fix sidebar is always open when prefers-reduced-motion is available

.changeset/nasty-planes-rhyme.md, packages/shared/__tests__/astish.test.ts, packages/shared/src/astish.ts
Closes https://github.com/chakra-ui/panda/issues/855
Fix the `astish` shared function when using `config.syntax: 'template-literal'`
ex:
```ts
css`${someVar}`
```
if a value is unresolvable in the static analysis step, it would be interpreted as `undefined`, and `astish` would
throw:
> TypeError: Cannot read properties of undefined (reading 'replace')
no
=> fix(shared): add fallback on astish value

.changeset/smooth-dragons-check.md, extension/vscode/src/index.ts
Enable extension in .astro/svelte/vue files
no
--- 
thanks @pawelblaszczyk5 for catching this
=> feat(vscode): enable extension in astro/svelte/vue files

.changeset/three-spiders-turn.md, packages/parser/src/parser.ts
Closes # discord issue https://discord.com/channels/1118988919804010566/1124374872345292913/1124383942552866846
Do not allow all JSX properties to be extracted if none provided, rely on the `isStyleProp` fn instead
when:
- `eject: true` and only the `@pandacss/preset-base` is used (or none)
- some non-styling JSX prop is extracted leading to an incorrect CSS rule being generated, ex:
```sh
🐼 info [cli] Writing /Users/astahmer/dev/reproductions/remix-panda/styled-system/debug/app__routes___index.css
🐼 error [serializer:css] Failed to serialize CSS: CssSyntaxError: <css input>:28:19: Missed semicolon
26 |     }
27 |     .src_https\:\/\/akmweb\.viztatech\.com\/web\/svnres\/file\/50_e4bb32c9ea75c5de397f2dc17a3cf186\.jpg {
> 28 |         src: …
```
=> fix(parser): never allow all JSX props to be extracted

.changeset/smart-mirrors-call.md, packages/generator/src/artifacts/css/flat-css.ts, packages/studio/styled-system/helpers.mjs
Closes https://github.com/chakra-ui/panda/discussions/899
Fix reset.css (generated when config has `preflight: true`) import order, always place it first so that it can be easily
overriden
no
=> fix(generator): reset.css import order

.changeset/new-islands-play.md, packages/shared/__tests__/walk-object.test.ts, packages/shared/src/walk-object.ts
Closes https://github.com/chakra-ui/panda/issues/877
Fix issue where the `walkObject` shared helper would set an object key to a nullish value
```ts
const shorthands = {
flexDir: 'flexDirection',
}
const obj = {
flexDir: 'row',
flexDirection: undefined,
}
const result = walkObject(obj, (value) => value, {
getKey(prop) {
return shorthands[prop] ?? prop
},
})
```
This would set the `flexDirection` to `row` (using `getKey`) and then set the `flexDirection` property again, this time
to `undefined`, since it existed in the original object
I'm not sure ? @segunadebayo
=> fix(shared): walkObject set prop with nullish value

website/src/components/nav-link.tsx, website/src/components/navbar.desktop.tsx, website/src/components/navbar.mobile.tsx
Closes # 
This pr adds the optional prop for `Navlink` to make the link as external when needed (repo link)
clicking Github link in the nav will not open a new tap
clicking links that should open new tab (external links) opens a new tap
no
=> chore(website): enhance navbar link

.changeset/chilled-cheetahs-search.md, packages/studio/astro.config.mjs, packages/studio/package.json, packages/studio/virtual-panda.mjs
running `panda studio` (with or without `--build`) was not working when used outside of our monorepo
no
this was the stacktrace, tried updating `vite.external` but no luck
```sh
❯ pnpm panda studio 
serveStudio
➜  Build: use --build to build
11:55:43 PM [vite] Error when evaluating SSR module /@fs/Users/astahmer/dev/open-source/panda/node_modules/.pnpm/postcss@8.4.24/node_modules/postcss/lib/postcss.js:
|- ReferenceError: require is not defined
at eval (/Users/astahmer/dev/open-source/panda/node_modules/.pnpm/postcss@8.4.24/node_modules/postcss/lib/postcss.js:5:22)
at instantiateModule (file:///Users/astahmer/dev/open-source/panda/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:15)
11:55:43 PM [vite] Error when evaluating SSR …
```
=> fix(studio): dev/build outside of monorepo

website/pages/docs/concepts/patterns.md, website/pages/docs/customization/patterns.mdx
=> docs(patterns): mention jsxElement

.changeset/mean-carpets-fly.md, packages/generator/src/artifacts/index.ts, packages/generator/src/artifacts/js/is-valid-prop.ts, packages/studio/styled-system/jsx/index.d.ts, packages/studio/styled-system/jsx/index.mjs, packages/studio/styled-system/jsx/is-valid-prop.d.ts
Export `isCssProperty` helper function from styled-system/jsx
It is mostly useful to make a wrapper around `styled` factory function, so split properties between style props & custom ones
no
=> feat(generator): export isCssProperty from /jsx

.changeset/chilled-shrimps-flow.md, packages/node/src/extract.ts
Closes #936.
This PR contains the fix for using `panda cssgen` with `--outfile`, which would not emit the files correctly.
When using `cssgen` with `outfile` option, it would not emit CSS of files.
It now extracts the files to chunks before bundling them into a CSS file.
No
=> fix(node): extract files before bundling CSS into an outfile

website/pages/docs/references/config.md
Adds info in the docs about the syntax config.
No
I wasn't sure which h2 heading this info fit under, so let me know if it should move to something else.
=> docs: add info about syntax config

website/pages/docs/getting-started/postcss.mdx
Removes instruction about `autoprefixer`
Mentions adding `autoprefixer `
Does not mention `autoprefixer `
No
If `autoprefixer` is suggested, it should be added to the added to the code snippet
=> Remove instruction about autoprefixer

.changeset/rotten-kids-develop.md, packages/core/src/recipes.ts, packages/generator/src/generator.ts, packages/parser/__tests__/output.test.ts, packages/parser/src/parser.ts
originally issued on discord with this minimal repro repo https://github.com/snowball-tech/fractal
Closes #861
Fix JSX recipe extraction when multiple recipes were used on the same component, ex:
```tsx
const ComponentWithMultipleRecipes = ({ variant }) => {
return (
<button className={cx(pinkRecipe({ variant }), greenRecipe({ variant }), blueRecipe({ variant }))}>Hello</button>
)
}
```
Given a `panda.config.ts` with recipes each including a common `jsx` tag name, such as:
```ts
recipes: {
pinkRecipe: {
name: 'pinkRecipe',
jsx: ['ComponentWithMultipleRecipes'],
base: { color: 'pink.100' },
variants: {
variant: {
small: { fontSize: 'sm' },
},
},
},
greenRecipe: {
name: 'greenRecipe',
jsx: ['ComponentWithMultipleRecipes'],
base: { color: 'green.100' },
variants: {
variant: {
small: { …
```
=> fix(recipes): multiple recipes on 1 JSX element

.changeset/purple-ads-hammer.md, packages/extractor/__tests__/extract.test.ts, packages/extractor/src/maybe-box-node.ts, packages/parser/__tests__/output.test.ts, packages/studio/styled-system/helpers.mjs
Closes https://github.com/chakra-ui/panda/discussions/970
Resolve identifier default value from parameter, code like `position` and `inset` here:
```tsx
export const Positioned: React.FC<PositionedProps> = ({ children, position = 'absolute', inset = 0, ...rest }) => (
<styled.div position={position} inset={inset} {...rest}>
{children}
</styled.div>
)
```
no
=> fix(extractor): resolve identifier default value

packages/generator/__tests__/generate-reset.test.ts, packages/generator/src/artifacts/css/reset-css.ts, packages/studio/styled-system/helpers.mjs
Closes # 
The generated reset.css has redundant indents and empty lines because template literals is formatted by prettier.
This causes the formatter(prettier) detects the diffs every time running `panda codegen`.
So, I added `prettier-ignore` at the reset.css string definition.
The generated reset.css likes below
```css
/* reset.css */
@layer reset {
* {
margin: 0;
padding: 0;
font: inherit;
}
...
}
```
```css
/* reset.css */
@layer reset {
* {
margin: 0;
padding: 0;
font: inherit;
}
...
}
```
=> Fix redundant indents and empty lines in reset.css

.changeset/mighty-ducks-mix.md, packages/studio/scripts/studio.ts
This PR fixes issues regarding `studio --build` command in case of using `pnpm` or linking dependencies locally
@astahmer is aware of this issue and we were in contact while solving it
Currently it throws errors about dependencies that it can't find, example error (shortened for brevity)
```
Cannot find package 'html-escaper' imported from /Users/pawelblaszczyk/dev/panda-studio-pnpm/styled-system-studio/src/pages/index.astro.mjs
Did you mean to import html-escaper@3.0.3/node_modules/html-escaper/cjs/index.js?
Error: Cannot find package 'html-escaper' imported from /Users/pawelblaszczyk/dev/panda-studio-pnpm/styled-system-studio/src/pages/index.astro.mjs
```
It should properly resolve the paths and cwd of the command now
I think no
I've tried to test it as far as it was possible for me …
=> fix: studio build adjustments with pnpm or linking

website/pages/docs/installation/storybook.mdx
When using PandaCSS in Storybook with the Vite builder, HMR is not working when modifying a recipe.
This is only due to a PostCSS configuration format.
My guess is that the Vite builder is generating a Vite configuration on the fly based on the `vite.config.*` file and other auto-detected parameters.  
The thing is that when inlining the PostCSS config in the Vite config, you **must** use the array format to define the plugin (see https://v2.vitejs.dev/config/#css-postcss).
This PR only mention this point in the "Storybook" dedicated page.
When you change a PandaCSS recipe, HMR in Storybook does not pick up the changes. You have to completely restart Storybook to see the changes.
When properly configured, Vite & PostCSS pick up the changes in recipes and properly triggers the HMR in …
=> docs(storybook): mention the weird Storybook+Vite & HMR case

.changeset/healthy-llamas-turn.md, packages/extractor/__tests__/extract.test.ts, packages/extractor/src/maybe-box-node.ts
Closes https://github.com/chakra-ui/panda/issues/1008
Fix extractor behaviour when encoutering operation tokens, try to evaluate them instead of resolving them as string
before:
```tsx
<AspectRatio ratio={1 / 2} asterisk={1 * 5} exp={1 ** 4} minus={5 - 1} />
```
would be extracted to:
```json
{
"asterisk": "1 *5",
"exp": "1**4",
"minus": "5 -1",
"ratio": "1 / 2",
}
```
now, it will be extracted to the actual values:
```json
{
"asterisk": 5,
"exp": 1,
"minus": 4,
"ratio": 0.5,
}
````
no
=> fix(extractor): eval nodes with operation tokens

.changeset/green-books-help.md, packages/parser/__tests__/vue.test.ts, packages/parser/src/vue-to-tsx.ts
Closes https://github.com/chakra-ui/panda/issues/998
Fix parser issue in .vue files, make the traversal check nested elements instead of only checking the 1st level
only check the 1st element
```vue
<template>
<div :class="css({ color: 'red', fontWeight: 'bold' })">  // ✅
<p>depth 1 children</p>
<div :class="css({ color: 'green' })">   // ❌
<p>depth 2 children</p>
</div>
</div>
</template>
```
checks all nested elements as well
no
=> fix(parser): vue nested element traversal

.changeset/popular-hornets-press.md, packages/node/src/builder.ts
Closes https://github.com/chakra-ui/panda/issues/1025
Fix postcss HMR when importing files in the panda.config file
We didnt register the dependencies found through the `getConfigDependencies` function to the postcss plugin process, sometimes it seems we find more file dependencies that esbuild (`ctx.dependencies`)
Use both esbuild found dependencies `ctx.dependencies` and those found from our own `getConfigDependencies` function 
no
=> fix(postcss): HMR when importing files in config

.changeset/sour-months-melt.md, packages/extractor/src/box.ts, packages/extractor/src/extract.ts, packages/parser/__tests__/css-2.test.ts
Closes #1022
This is ~~WIP~~ fix for issue #1022.
=> fix(extractor): Not working when I use SpreadSyntax and prop contains string that ends with ':'

.changeset/wild-deers-sin.md, packages/config/package.json, packages/config/src/get-mod-deps.ts, pnpm-lock.yaml
Closes https://discord.com/channels/1118988919804010566/1126883096067850393/1129043920643424337
Fix issue where hot module reloading is inconsistent in the PostCSS plugin when another internal typescript-only package is changed
-> if a monorepo internal package only use TS files, without a dist folder, it seems esbuild can't properly resolve config dependencies.
this kind of internal package with a package.json would be an issue:
```json
"main": "./src/index.ts",
"types": "./src/index.ts",
```
no
minimal repro here 
https://github.com/rcoedo/pandacss-pnpm-turbo
=> fix(postcss): use ts.resolveModuleName

website/pages/docs/concepts/recipes.md
This pull request fixes 2 broken links in the `/docs/concepts/recipes` page.
Two links are broken due to the missing `/docs` prefix in the URL which leads to a 404 error.
The two links now point to the correct anchors in the same page.
No
N/A
=> fix(docs): recipes broken links

packages/extractor/package.json, packages/extractor/src/find-identifier-value-declaration.ts, packages/extractor/src/get-object-literal-expression-prop-pairs.ts, packages/extractor/src/maybe-box-node.ts, pnpm-lock.yaml
it was very useful while developing the extractor but now that it's stable, it renders `PANDA_DEBUG` useless because of the spam
no
=> chore(extractor): rm logs

website/pages/docs/concepts/writing-styles.md
=> fix(docs): fixing syntax error

.changeset/mighty-pianos-know.md, packages/config/src/get-mod-deps.ts
value "Node" doesn't exist in browser, which crashed the playground, omit it when passing options to TS and use a try/catch to make this part safer
no
=> fix(config): ts.compilerOptions.moduleResolution in browser

.changeset/gold-apples-brush.md, packages/core/src/atomic-rule.ts, packages/extractor/src/extract.ts, packages/parser/src/parser.ts
Discord issue https://discord.com/channels/1118988919804010566/1131248934405279836/1131250656213213286
reproduction here: https://github.com/widgetbot-io/message-renderer/blob/15ad1d4faefa66c21a53be96ece3037750a5265b/src/markdown/render/elements/mentions/style.ts#L7-L35
Fix cases where Stitches `styled.withConfig` would be misinterpreted as a panda fn and lead to this error:
```ts
TypeError: Cannot read properties of undefined (reading 'startsWith')
at /panda/packages/shared/dist/index.js:433:16
at get (/panda/packages/shared/dist/index.js:116:20)
at Utility.setClassName (/panda/packages/core/dist/index.js:1682:66)
at inner (/panda/packages/core/dist/index.js:1705:14)
at Utility.getOrCreateClassName (/panda/packages/core/dist/index.js:1709:12)
at AtomicRule.transform …
```
=> fix(core): assert that styleObject is an object

.changeset/eighty-hats-speak.md, packages/node/src/setup-config.ts
Closes # 
Add missing command when generating panda config
When init the panda config with the following command:
```
pnpm exec panda init -p --syntax template-literal --jsx-framework react
```
The generated config was:
```ts
import { defineConfig } from "@pandacss/dev"
// Whether to use css reset
preflight: true,
// Where to look for your css declarations
include: ["./src/**/*.{js,jsx,ts,tsx}", "./pages/**/*.{js,jsx,ts,tsx}"],
// Files to exclude
exclude: [],
// Useful for theme customization
theme: {
extend: {}
},
// The output directory for your css system
outdir: "styled-system",
// The JSX framework to use
jsxFramework: 'react'
// The CSS Syntax to use to use
syntax: 'template-literal'
})
```
which was missing the `,` seperator between the `jsxFramework` …
=> Adding missing comma for generated panda config

.changeset/quiet-toys-tell.md, extension/language-server/package.json, package.json, packages/extractor/package.json, packages/extractor/src/evaluate-node.ts, packages/node/package.json, packages/parser/package.json, packages/studio/styled-system/tokens/index.css, pnpm-lock.yaml
Closes https://github.com/chakra-ui/panda/issues/1008#issuecomment-1646967843
Fix node evaluation in extractor process (can happen when using a BinaryExpression, simple CallExpression or conditions)
Also updated `ts-morph` version to match the one from `typescript` so there is no mismatch in the `SyntaxKind` enum which can cause subtle issues such as the ones linked above
no
we should probably never update `typescript` without updating `ts-morph` as well
=> fix(extractor): never override node/ts

.changeset/angry-years-mate.md, packages/generator/__tests__/generate-recipe.test.ts, packages/generator/src/artifacts/js/recipe.ts, packages/parser/__tests__/output.test.ts, packages/studio/styled-system/tokens/index.css
related to: https://github.com/chakra-ui/panda/issues/1093
Adds the `{recipe}.raw()` in generated runtime (my bad I had only added the typings)
Fix test case (was using `sm` instead of `small`)
no
=> fix(recipes): add .raw fn & fix test case

website/pages/docs/references/cli.md
- Fixed minor typos and grammar in CLI reference docs
- Normalized punctuation to match the majority of the existing copy (period at end of CLI subcommand description, no punctuation at end of flag descriptions)
- CLI reference documentation only (no direct Panda impact)
- CLI reference documentation only (no direct Panda impact)
No
N/A
=> docs(cli): fix minor typos and grammar

.changeset/spotty-bugs-tease.md, packages/node/src/builder.ts, packages/postcss/src/index.ts
Closes https://github.com/chakra-ui/panda/issues/1120
Fix PostCSS edge-case where the config file is not in the app root
no
fix(postcss): pass cwd or fallback to process.cwd in builder
can't use dirname(configPath) because sometimes the config path is somewhere else than in the app root
also, don't throw on missing file
=> fix(postcss): pass cwd or fallback to process.cwd in builder

.changeset/red-ads-mate.md, packages/generator/__tests__/generate-prop-types.test.ts, packages/preset-base/src/utilities/effects.ts, packages/studio/styled-system/jsx/is-valid-prop.mjs, packages/studio/styled-system/types/prop-type.d.ts
Add the `opacity` utility to the base preset.
=> feat(preset-base): add opacity utility

playground/src/components/Preview/index.tsx
Fix inability to use `Important` in playground
=> playground: fix `!important` usage

website/pages/docs/overview/getting-started.mdx
Closes # 
> I was going through the getting started docs on how to use Panda CSS and the sentence under the Framework Guides header began with "Starting" instead of "Start" and I thought to fix that 😄
> A minor typo that may be off-putting
> Will fix the typo and may improve readability
No
=> Minor typo fix in the getting-started.mdx page

.changeset/famous-avocados-play.md, packages/config/src/resolve-ts-path-pattern.ts
Closes #1130 
Described in the issue.
Pattern style was not generated in windows.
Works as expected.
No
=> fix: mixed path separator during tsconfig path mapping

.changeset/famous-nails-reflect.md, packages/cli/src/cli-main.ts, packages/node/src/extract.ts
Add an optional `glob` argument that overrides the config.include on the `panda cssgen` CLI command.
This can be used to generate `.css` files for a specific part of an app, for example you could generate a .css for each page so that you'd only include what you need.
no
also add more types on flags
=> feat(cli): cssgen glob optional argument

website/pages/docs/concepts/style-props.mdx
JSXStyleProps is not exported!
The correct name is JsxStyleProps. 
This PR fix de documentation change JSXStyleProps to JsxStyleProps
Closes # 
=> fix: import name JsxStyleProps

.changeset/tough-gifts-bathe.md, packages/generator/src/artifacts/solid-jsx/jsx.ts
Closes # 
> when using the styled function with a recipe for solid-js, no style are produced
example:
```
import { styled } from 'styled-system/jsx'
import { button } from 'styled-system/recipes'
export const Button = styled('button', button)
```
> add the  missing test ```|| configOrCva.__recipe__``` to check if a recipe is passed to the styled function.
[The test is the same as in react framework for example](https://github.com/chakra-ui/panda/blob/cc4d2fc02d0bb9000790624111aa8c1ae7818d97/packages/generator/src/artifacts/react-jsx/jsx.ts#L16) and [it is missing in the current version (0.11.1)](https://github.com/chakra-ui/panda/blob/cc4d2fc02d0bb9000790624111aa8c1ae7818d97/packages/generator/src/artifacts/solid-jsx/jsx.ts#L16)
No
=> fix failed styled component for solid-js when using recipe

playground/src/hooks/usePlayground.ts
Set `jsxFramework` by default in playground
=> playground: set `jsxFramework` by default

.changeset/tough-dots-burn.md, packages/generator/src/artifacts/css/parser-css.ts, packages/generator/src/engines/pattern.ts, packages/parser/__tests__/output.test.ts
Closes https://github.com/chakra-ui/panda/issues/1260
Fix an issue with custom JSX components not finding their matching patterns
Given this config:
```
patterns: {
extend: {
circle: {
jsx: ["Circle", "CustomCircle"],
},
},
},
```
and usage like:
```
import CustomCircle from './CustomCircle'
function App() {
return <CustomCircle size={16} backgroundColor="blue" />
}
```
the `CustomCircle` was trying to find a pattern named `customCircle` instead of being matched to the `circle` pattern
no
=> fix(patterns): custom JSX pattern matching

.changeset/smart-mails-train.md, packages/generator/src/artifacts/js/css-fn.ts, packages/studio/styled-system/css/css.d.ts
Closes https://github.com/chakra-ui/panda/pull/1264#issuecomment-1698394167
`css(...args)` are already filtered to only take objects, this PR makes the typings lenient with falsy values, mostly intended for component props that have optional values like `cssProps?: SystemStyleObject` and then later `css({ ... }, cssProps)`
no
=> types: make css(...args) allow falsy values

playground/src/app/[id]/page.tsx, playground/src/hooks/usePlayground.ts
Closes # 
I was reading `playground` workspace code, and found some typo.(initialState)
minor typo
```ts
export type UsePlayGroundProps = {
intialState?: State | null // typo initialState
}
```
Will fix the typo
```ts
export type UsePlayGroundProps = {
initialState?: State | null // fix
}
```
No
=> fix(playground): fix typo intialState to initialState

.changeset/ten-zebras-trade.md, packages/core/__tests__/expand-token-fn.test.ts, packages/core/src/plugins/expand-token-fn.ts, packages/studio/styled-system/chunks/..__core____tests____expand-token-fn.test.css, packages/studio/styled-system/styles.css
Fix issue with the `token()` function in CSS strings that produced CSS syntax error when non-existing token were left
unchanged (due to the `.`)
```css
* {
color: token(colors.magenta, pink);
}
```
```css
* {
color: token('colors.magenta', pink);
}
```
no
=> fix: `token()` CSS syntax error when non-existing

.changeset/mean-monkeys-jam.md, packages/generator/__tests__/generate-pattern.test.ts, packages/generator/src/artifacts/js/pattern.ts
Make `raw` interface for the patter to match `getPatternStyle`method.
`raw` pattern method definition have `styles` argument as mandatory even though the corresponding `get<PatternName>Style` method have style argument as optional.
make `raw` pattern method `style` argument optional, so `pattern.raw()` is a valid call
No
=> fix: pattern.raw shares same signature as getPatternStyle

.changeset/polite-shoes-attack.md, packages/core/__tests__/utility.test.ts, packages/core/src/utility.ts, packages/types/src/utility.ts
The utility transform fn now allow retrieving the token object with the raw value/conditions as currently there's no way
to get it from there.
Example:
Given I have this config.tokens:
`colors: { redish: { value: '#9c1d1d' } }`
And this utility transform:
```ts
{
utilities: {
backgroundColor: {
shorthand: "bgColor",
className: "bg",
values: "colors",
transform(value, args) {
console.log({ value, args, raw: args.token(args.raw), fromPath: args.token('colors.' + args.raw) })
return {
backgroundColor: `rgba(${convertToRgba(value)}, var(--panda-text-opacity))`,
};
},
},
},
}
```
the output log would be
```ts
{
value: 'var(--colors-redish)',
args: { token: [Function: bound getToken], raw: 'redish' },
raw: undefined,
fromPath: 'var(--colors-redish)'
}
```
now it can be retrieved like this:
``` …
```
=> feat(utility): allow retrieving the token object

.changeset/chilly-jobs-try.md, packages/cli/src/index.ts
Closes #1317  
Adds `RecipeConfig` and `RecipeVariantRecord` to the type exports.
Types targeting recipe configs are not exported in @pandacss/dev. Slot recipes do not face this issue as they are exported.
Adding recipe-related types fixes this issue in particular (and my own use case).
No
That being said, `PatternConfig` and `Parts` might want to be exported too (let me know if that's needed too and I'll make the changes)
=> fix(cli): add missing recipe type exports

.changeset/eight-lies-sing.md, packages/types/src/tokens.ts
Closes #1330 
both `zIndex` and `opacity` tokens can of course be css custom properties. Forcing them to a number precludes this notion.
Currently, when passing a custom property as the `value` of a `zIndex` or `opacity` token, you get this ts error:
```ts
zIndex: {
1: { value: 'var(--layer-1)' },
}
```
> Type 'string' is not assignable to type 'number | Token<number> | Recursive<Token<number>>'.ts(2322)
This theoretically makes sense, but it doesn't account for css custom properties.
This pr brings `opacity` and `zIndex` inline with the other token values and makes it possible to set them as a `string`.
No, it adds options rather than removing them.
This came up as I was implementing an [open props](https://open-props.style/) theme in panda.
=> fix: allow `string` as opacity and zIndex tokens

.changeset/quick-oranges-mix.md, packages/generator/src/artifacts/js/cva.ts, packages/studio/styled-system/css/cva.mjs
Fix issue with cva when using compoundVariants and not passing any variants in the usage (ex: `button()` with
`const button = cva({ ... })`)
no
Note: since `cva` runtime implementation is also used for config recipe, it fixes both
=> fix(cva): add optional chaining on assertCompoundVariant

.changeset/shy-poets-warn.md, packages/node/src/classify.ts, packages/parser/__tests__/output.test.ts, packages/parser/src/parser.ts, packages/studio/styled-system/types/recipe.d.ts, packages/types/src/shared.ts
slightly tweak the `DeepPartial` type to skip a few steps`compoundVariants`
that's a 10s down in both cases for the ts checker speed, mostly from the DeepPartial change. this is pretty important for the DX when editing the panda.config.ts
when using compoundVariants, that's also few hundreds ms cut (600 in my local repo)
before DeepPartial change:
after DeepPartial change:
before DeepPartial change:
after DeepPartial change:
```sh
pnpm tsc -p tsconfig.debug.json --outDir perf-issue  --generateTrace trace-dir 
npx @typescript/analyze-trace trace-dir --forceMillis=100 --skipMillis=50
```
tsconfig.debug.json
```ts
{
"compilerOptions": {
"skipLibCheck": true
},
"include": ["panda.config.ts"]
}
```
no
- it looks like `SystemProperties` / `CssVarProperties` are the main culprit. I quickly tried …
=> perf(types): faster DeepPartial

.changeset/stupid-lions-know.md, packages/extractor/__tests__/extract.test.ts, packages/extractor/src/utils.ts
Closes https://github.com/chakra-ui/panda/issues/1360
Fix issue where the `satisfies` would prevent an object from being extracted
no
=> fix(extractor): handle satisfies keyword

.changeset/brave-geese-doubt.md, packages/extractor/__tests__/extract.test.ts, packages/extractor/src/unbox.ts
Closes # https://github.com/chakra-ui/panda/issues/1365
Fix issue with the `unbox` fn that removed nullish values, which could
be useful for the [Array Syntax](https://panda-css.com/docs/concepts/responsive-design#the-array-syntax)
```ts
const className = css({
color: ['black', undefined, 'orange', 'red'],
})
```
no
=> fix(#1365): keep extracted nullish values

.changeset/three-birds-know.md, packages/generator/src/artifacts/css/reset-css.ts
Closes #1378
Add the property `-moz-osx-font-smoothing: grayscale;` to the `reset.css` under the `html` selector.
No
=> fix(generator): add font smoothing for firefox macos

.changeset/lucky-dots-report.md, packages/extractor/src/types.ts, packages/parser/__tests__/output.test.ts, packages/parser/__tests__/ts-eval.bench.ts, packages/parser/src/parser.ts, website/pages/docs/guides/dynamic-styling.md
Closes https://github.com/chakra-ui/panda/issues/1370#issuecomment-1719289977 https://github.com/chakra-ui/panda/pull/1333 https://github.com/chakra-ui/panda/discussions/1332
feat(parser): extract {fn}.raw as an identity fn
so this will now work:
```ts
import { css } from 'styled-system/css'
const paragraphSpacingStyle = css.raw({
'&:not(:first-child)': { marginBlockEnd: '1em' },
})
export const proseCss = css.raw({
maxWidth: '800px',
'& p': {
'&:not(:first-child)': { marginBlockStart: '1em' },
},
'& h1': paragraphSpacingStyle,
'& h2': paragraphSpacingStyle,
})
```
& use ECMA preset for ts-evaluator: This means that no other globals than those that are defined in the ECMAScript spec
such as Math, Promise, Object, etc, are available but it allows for some basic evaluation of expressions …
=> feat(parser): smarter parser

.changeset/purple-impalas-sneeze.md, packages/generator/__tests__/generate-token.test.ts, packages/token-dictionary/__tests__/docs.test.ts, packages/token-dictionary/__tests__/format-vars.test.ts, packages/token-dictionary/__tests__/tokens.test.ts, packages/token-dictionary/__tests__/transform-border.test.ts, packages/token-dictionary/src/token.ts
Closes #1196
Tis PR implements the reuse of css variable in semantic token alias/references.
For example:
```
const tokens = {
colors: {
red: {
value: '#ef4444',
},
},
colors: {
danger: { value: '{colors.red}' },
},
},
}
```
will output:
```
--colors-red: #ef4444;
--colors-danger: #ef4444;
```
will output:
```
--colors-red: #ef4444;
--colors-danger: var(--colors-red);
```
No
=> feat: reuse css variable in semantic token alias

.changeset/strange-moose-fix.md, packages/config/__tests__/merge-config.test.ts, packages/config/src/get-resolved-config.ts, packages/studio/styled-system/tokens/index.css, playground/src/lib/resolve-config.ts
> Note: This is only relevant for users using more than 1 custom defined preset that overlap with each other.
BREAKING CHANGE: Presets merging order felt wrong (left overriding right presets) and is now more intuitive (right
overriding left presets)
Example:
```ts
const firstConfig = definePreset({
theme: {
tokens: {
colors: {
'first-main': { value: 'override' },
},
},
extend: {
tokens: {
colors: {
orange: { value: 'orange' },
gray: { value: 'from-first-config' },
},
},
},
},
})
const secondConfig = definePreset({
theme: {
tokens: {
colors: {
pink: { value: 'pink' },
},
},
extend: {
tokens: {
colors: {
blue: { value: 'blue' },
gray: { value: 'gray' },
},
},
},
},
})
// Final config
presets: [firstConfig, secondConfig],
})
```
Here's the difference between the …
=> fix(BREAKING): presets merging order

website/pages/docs/customization/utilities.mdx
Deleting the token import. If the token function is supplied by the transform function it doesn't need to be (and probably shouldn't be) imported.
Closes # 
Docs update only
Docs incorrect
No
=> Docs: fixes error in utilities.mdx

website/pages/docs/concepts/recipes.md
As of v0.9, recipe's `name` was renamed to `className`.
=> Docs: Replace recipe.name with recipe.className

packages/generator/__tests__/generate-recipe.test.ts, packages/generator/src/artifacts/js/recipe.ts
I made a mistake in the [switch to interface PR](https://github.com/chakra-ui/panda/commit/26a788c0a9e85dfff40fabcf3d678016944954ff), this one fixes it
=> fix: recipe variant props conditional was removed

.changeset/gold-zebras-battle.md, packages/generator/__tests__/generate-recipe.test.ts, packages/generator/src/artifacts/js/recipe.ts, packages/generator/src/artifacts/qwik-jsx/types.string-literal.ts, packages/generator/src/artifacts/qwik-jsx/types.ts, packages/generator/src/artifacts/react-jsx/types.string-literal.ts, packages/generator/src/artifacts/react-jsx/types.ts, packages/generator/src/artifacts/types/main.ts, packages/generator/src/artifacts/vue-jsx/types.string-literal.ts, packages/generator/src/artifacts/vue-jsx/types.ts, packages/studio/styled-system/types/index.d.ts, packages/studio/styled-system/types/jsx.d.ts
Closes https://github.com/chakra-ui/panda/issues/1327
When bundling the `outdir` in a library, you usually want to generate type declaration files (`d.ts`). Sometimes TS will
complain about types not being exported.
- Export all types from `{outdir}/types/index.d.ts`, this fixes errors looking like this:
```
src/components/Checkbox/index.tsx(8,7): error TS2742: The inferred type of 'Root' cannot be named without a reference to '../../../node_modules/@acmeorg/styled-system/types/system-types'. This is likely not portable. A type annotation is necessary.
src/components/Checkbox/index.tsx(8,7): error TS2742: The inferred type of 'Root' cannot be named without a reference to '../../../node_modules/@acmeorg/styled-system/types/csstype'. This is likely not portable. A type annotation is …
```
=> codegen: export needed types to bundle outdir

.changeset/silent-spies-design.md, packages/types/src/theme.ts, packages/types/src/utility.ts
Closes https://github.com/chakra-ui/panda/issues/1430
- Fix `ExtendableUtilityConfig` typings after a regression in 0.15.2 (due to
https://github.com/chakra-ui/panda/pull/1410)
- Fix `ExtendableTheme` (specifically make the `RecipeConfig` Partial inside the `theme: { extend: { ... } }` object),
same for slotRecipes
no
=> types: fix ExtendableUtilityConfig

.changeset/sixty-wombats-occur.md, packages/extractor/src/unbox.ts, packages/parser/__tests__/output.test.ts
Fix static extraction of the [Array Syntax](https://panda-css.com/docs/concepts/responsive-design#the-array-syntax) when
used with runtime conditions
Given a component like this:
```ts
function App() {
return <Box py={[2, verticallyCondensed ? 2 : 3, 4]} />
}
```
the `py` value was incorrectly extracted like this:
```ts
{
"py": {
"1": 2,
},
},
{
"py": {
"1": 3,
},
},
```
which would then generate invalid CSS like:
```css
.paddingBlock\\\\:1_2 {
1: 2px;
}
.paddingBlock\\\\:1_3 {
1: 3px;
}
```
it's now correctly transformed back to an array:
```diff
{
"py": {
-    "1": 2,
+   [
+       undefined,
+       2,
+   ]
},
},
{
"py": {
-    "1": 3,
+   [
+       undefined,
+       3,
+   ]
},
},
```
which will generate the correct CSS
```css
@media screen and (min-width: 40em) {
.sm\\\\:py_2 { …
```
=> fix(unbox): array syntax with conditionals

.changeset/pretty-lamps-tease.md, packages/generator/src/artifacts/css/flat-css.ts, packages/generator/src/artifacts/css/global-css.ts, packages/generator/src/artifacts/css/keyframe-css.ts, packages/generator/src/artifacts/css/parser-css.ts, packages/generator/src/artifacts/css/reset-css.ts, packages/generator/src/artifacts/css/static-css.ts, packages/generator/src/artifacts/css/token-css.ts, packages/node/src/builder.ts, packages/node/src/debug-files.ts, packages/node/src/extract.ts, packages/node/src/output-engine.ts
Closes #1435
This PR refactors all promises to use `Promise.allSettled` to avoid early aborting of the promise chain.
Fails intermittently
Should work as expected
No
=> refactor: use `promise.allSettled`

.changeset/curvy-keys-sparkle.md, packages/generator/src/artifacts/qwik-jsx/types.ts
Closes #1507 
There was a missing `Assign` inside the component typings.
Qwik typings were broken.
Qwik typings are now working
No
The issue describes this in greater detail.
=> fix(generator): fix qwik component typings

.changeset/many-apes-love.md, packages/cli/src/cli-main.ts, packages/cli/src/types.ts, packages/generator/src/generator.ts, packages/node/src/extract.ts, packages/node/src/generate.ts, packages/node/src/index.ts, website/pages/docs/references/cli.md
Adds a new `--minimal` flag for the CLI on the `panda cssgen` command to skip generating CSS for theme tokens,
preflightkeyframes, static and global css
Thich means that the generated CSS will only contain the CSS related to the styles found in the included files.
> Note that you can use a `glob` to override the `config.include` option like this:
> `panda cssgen "src/**/*.css" --minimal`
This is useful when you want to split your CSS into multiple files, for example if you want to split by pages.
Use it like this:
```bash
panda cssgen "src/**/pages/*.css" --minimal --outfile dist/pages.css
```
---
In addition to the optional `glob` that you can already pass to override the config.include option, the `panda cssgen`
command now accepts a new `{type}` argument to generate only a specific …
=> feat(cli): cssgen --minimal / cssgen of type

.changeset/slimy-ducks-beg.md, packages/core/__tests__/fixture.ts, packages/core/__tests__/slot-recipe.test.ts, packages/core/src/recipes.ts
Automatically add each recipe slots to the `jsx` property, with a dot notation
```ts
const button = defineSlotRecipe({
className: 'button',
slots: ['root', 'icon', 'label'],
// ...
})
```
will have a default `jsx` property of: `[Button, Button.Root, Button.Icon, Button.Label]`
no
=> feat: better slot recipe jsx defaults

.changeset/mean-dogs-type.md, packages/node/src/create-context.ts
Closes https://github.com/chakra-ui/panda/issues/1451
Apply `config.logLevel` from the Panda config to the logger in every context.
no
=> fix(#1451): apply config.logLevel in context

.changeset/bright-worms-live.md, packages/generator/__tests__/cleanup-selector.test.ts, packages/generator/src/artifacts/css/token-css.ts
Closes https://github.com/chakra-ui/panda/issues/1506#issuecomment-1753829797
Fix an issue with the `@layer tokens` CSS declarations when using `cssVarRoot` with multiple selectors, like
`root, :host, ::backdrop`
no
=> fix(#1506): cssVarRoot issue with multiple selectors

website/pages/docs/guides/component-library.md
example should be wrapped in `value`
=> chore: fix tokens example

packages/cli/README.md, packages/cli/package.json
Closes [no issue that I'm aware of - I thought it'd be quicker/more helpful to open a PR directly]
This adds some optional package.json content that makes the npm page for `@pandacss/dev` more welcoming.
When a user like me who doesn't usually memorise GitHub URLs wants to look for the information for a certain package, or the version history of it, goes to `https://npmjs.com/package/@pandacss/dev` (which is easier to remember because the package name is in my local package.json) - I see no helpful links to the GitHub repo, or the docs site, or really anything:
The user will see:
- A couple of lines in the readme describing what the package is
- A link in the sidebar to the github repo which navigates to the cli package specifically
- A link in the sidebar to pandacss.com
- A count of …
=> Add @pandacss/dev npm package niceties

.changeset/large-turtles-call.md, packages/cli/README.md, packages/node/package.json, packages/node/src/builder.ts, packages/node/src/extract.ts, pnpm-lock.yaml
Closes #1496
This PR fixes the intermittent failures in several build contexts when running `panda codegen` in an npm script. Limiting the write concurrency should stabilize the process and reduce (if not eliminate the errors)
Codegen fails randomly
Work more consistently
No
=> fix: codegen write concurrency

.changeset/soft-seahorses-provide.md, packages/extractor/__tests__/extract.test.ts, packages/extractor/src/find-identifier-value-declaration.ts, packages/extractor/src/maybe-box-node.ts
Closes https://github.com/chakra-ui/panda/issues/1572
Extract identifier values coming from an `EnumDeclaration` member
Example:
```ts
enum Color {
Red = 'red.400',
Blue = 'blue.400',
}
const className = css({ color: Color.Red, backgroundColor: Color['Blue'] })
```
no
=> feat(extractor): EnumDeclaration

.changeset/beige-geese-impress.md, packages/node/src/builder.ts, packages/postcss/src/index.ts
This PR fixes a long-standing issue where CI builds fail randomly due to the PostCSS plugin emitting the codegen artifacts again in the middle of a build
Inconsistent build results
Fixed permanently. We avoid re-running the codegen within the PostCSS process
No
=> fix: postcss and emit failures in CI

.changeset/hip-gorillas-sleep.md, packages/generator/__tests__/generate-reset.test.ts, packages/generator/src/artifacts/css/reset-css.ts, packages/studio/styled-system/reset.css
In Safari there's default blue text color for some tags including button. It might cause pitfall in some cases.
For comparison Tailwind preflight resets button color.
```css
button,
input,
optgroup,
select,
textarea {
font-family: inherit;
font-feature-settings: inherit;
font-variation-settings: inherit;
font-size: 100%;
font-weight: inherit;
line-height: inherit;
color: inherit;
margin: 0;
padding: 0;
}
```
Some tag's text color is set to blue by Safari's user agent stylesheet.
```css
button,
input,
optgroup,
select,
textarea {
color: inherit;
}
```
Maybe, but in a good way?
=> fix: reset css button color style

.changeset/sweet-ears-drop.md, packages/cli/bin.js, packages/cli/src/cli-main.ts, packages/postcss/entry.js, packages/postcss/package.json, packages/studio/package.json, packages/studio/styled-system/reset.css, packages/symlink/package.json, pnpm-lock.yaml
Closes https://github.com/chakra-ui/panda/discussions/1584#discussioncomment-7398211
Fix an issue with the CLI, using the dev mode instead of the prod mode even when installed from npm.
This resolves the following errors:
```
Error: Cannot find module 'resolve.exports'
```
```
Error: Cannot find module './src/cli-main'
```
=> fix(cli): deps and dev mode detection

.changeset/tame-jars-whisper.md, packages/node/src/builder.ts
Fix an issue with the Postcss builder config change detection, which triggered unnecessary a rebuild of the artifacts.
=> fix(postcss): config change detection

website/pages/docs/theming/text-styles.md
The example for text-styles shows fontSize without a unit which has no effect on the styles. 
As someone new to panda this could be confusing. In some frameworks that have a set of default font sizings, a unitless fontSize might be valid.
=> docs: update text-styles

.changeset/hot-mangos-sip.md, .prettierignore, packages/studio/src/components/semantic-color.tsx
Display semantic colors correctly in studio.
**Before**
**After**
=> studio: display semantic colors correctly

.changeset/big-toes-obey.md, packages/generator/src/artifacts/solid-jsx/jsx.ts
Closes #1563 
Fix issue where Solid.js styled factory fails with pattern styles includes a css variable (e.g. Divider)
Throws
Works
No
=> fix: solid.js styled factory

.changeset/brave-planets-cheat.md, packages/cli/src/cli-main.ts, packages/node/src/analyze-tokens.ts, packages/node/src/ship-files.ts
Closes # https://github.com/chakra-ui/panda/discussions/1616
Ensure dir exists before writing file for the `panda ship` and `panda analyze` commands
no
=> fix(cli): cssgen/ship/analyze ensure dir exists before writing file

.changeset/curly-adults-accept.md, packages/studio/src/components/semantic-color.tsx
Improve semantic colors in studio 
**Before**
**After**
=> Improve semantic colors in studio

website/pages/docs/theming/tokens.md
>  Documentation provides an example of assets declaration that has a typo
>  Fix `assets` example in documentation
> change property `url` to `value`, matching type `Asset`
No
=> docs: fix example of assets token definition

.changeset/lucky-beds-sin.md, packages/cli/src/cli-main.ts, packages/cli/src/types.ts, packages/node/src/debug-files.ts
Add a `--only-config` flag for the `panda debug` command, to skip writing app files and just output the resolved config.
=> feat(cli): debug --only-config

.changeset/witty-months-bake.md, packages/core/__tests__/breakpoints.test.ts, packages/core/src/breakpoints.ts, packages/preset-base/src/utilities/display.ts, packages/studio/styled-system/types/conditions.d.ts
Closes #1571
Closes https://github.com/chakra-ui/panda/discussions/1523
- Fix issue where `hideBelow` breakpoints are inclusive of the specified breakpoints
```jsx
css({ hideBelow: 'lg' })
// => @media screen and (max-width: 63.9975em) { background: red; }
```
- Support arbitrary breakpoints in `hideBelow` and `hideFrom` utilities
```jsx
css({ hideFrom: '800px' })
// => @media screen and (min-width: 800px) { background: red; }
```
=> fix(utility): breakpoint inconsistency and support custom value

.changeset/lazy-rice-move.md, packages/generator/__tests__/generate-pattern.test.ts, packages/parser/__tests__/output.test.ts, packages/preset-base/src/patterns.ts, packages/studio/styled-system/patterns/grid.mjs, sandbox/preact-ts/src/app.tsx
Closes https://github.com/chakra-ui/panda/issues/1637
Fix an issue with the `grid` pattern from @pandacss/preset-base (included by default), setting a minChildWidth wasn't
interpreted as a token value
Before:
```tsx
<div className={grid({ minChildWidth: '80px', gap: 8 })} />
// ✅ grid-template-columns: repeat(auto-fit, minmax(80px, 1fr))
<div className={grid({ minChildWidth: '20', gap: 8 })} />
// ❌ grid-template-columns: repeat(auto-fit, minmax(20, 1fr))
//                                                  ^^^
```
After:
```tsx
<div className={grid({ minChildWidth: '80px', gap: 8 })} />
// ✅ grid-template-columns: repeat(auto-fit, minmax(80px, 1fr))
<div className={grid({ minChildWidth: '20', gap: 8 })} />
// ✅ grid-template-columns: repeat(auto-fit, minmax(var(--sizes-20, 20), 1fr))
// …
```
=> fix(#1637) grid minChildWidth value

packages/generator/src/messages.ts
Corrects a very minor grammar issue in the messaging produced after running `codegen`
When `codegen` is run, the message describing `styled-system/patterns` is as follows
> ✔️ `styled-system/patterns`: functions to implement apply common layout patterns
When `codegen` is run, the message describing `styled-system/patterns` is as follows
> ✔️ `styled-system/patterns`: functions to implement and apply common layout patterns
No
N/A
=> docs: correct sentence structure grammar

.changeset/wicked-emus-mix.md, packages/core/src/recipes.ts, packages/parser/__tests__/output.test.ts
Closes #1625
Fix issue where recipe artifacts might not match the recipes defined in the theme due to the internal cache not being
cleared as needed.
=> fix: recipe cache mismatch with theme.recipes

website/pages/docs/utilities/_meta.json, website/pages/docs/utilities/flex-and-grid.md, website/pages/docs/utilities/helpers.md, website/pages/docs/utilities/interactivity.md, website/pages/docs/utilities/layout.md, website/pages/docs/utilities/typography.md
=> docs: Update utilities

.changeset/heavy-tips-train.md, packages/core/src/utility.ts, packages/generator/__tests__/generate-prop-types.test.ts, packages/generator/src/artifacts/types/prop-types.ts, packages/parser/__tests__/output.test.ts, packages/shared/src/arbitrary-value.ts, packages/shared/src/index.ts, packages/studio/styled-system/types/prop-type.d.ts, sandbox/codegen/__tests__/scenarios/strict.test.ts
Closes https://github.com/chakra-ui/panda/discussions/1001
Add an escape-hatch for arbitrary values when using `config.strictTokens`, by prefixing the value with `[` and suffixing
with `]`, e.g. writing `[123px]` as a value will bypass the token validation.
```ts
css({
// @ts-expect-error TS will throw when using from strictTokens: true
color: '#fff',
// @ts-expect-error TS will throw when using from strictTokens: true
width: '100px',
// ✅ but this is now allowed:
bgColor: '[rgb(51 155 240)]',
fontSize: '[12px]',
})
```
no
We've listened and more enhancements will come for the `config.strictTokens` DX, thank you for providing great feedback !
=> feat: strictTokens escape hatch for arbitrary values

.changeset/honest-frogs-wave.md, packages/generator/src/parser-options.ts, packages/parser/__tests__/output.test.ts, packages/types/src/config.ts, website/pages/docs/references/config.md
Add a shortcut for the `config.importMap` option
You can now also use a string to customize the base import path and keep the default entrypoints:
```json
{
"importMap": "@scope/styled-system"
}
```
is the equivalent of:
```json
{
"importMap": {
"css": "@scope/styled-system/css",
"recipes": "@scope/styled-system/recipes",
"patterns": "@scope/styled-system/patterns",
"jsx": "@scope/styled-system/jsx"
}
}
```
no
=> feat(config): importMap as string

playground/src/components/Editor.tsx, playground/src/components/icons.tsx, playground/src/hooks/useEditor.ts
Add wordwrap control to playground
https://github.com/chakra-ui/panda/assets/30869823/deea5917-48b3-43e1-a6b9-ec7191be78b4
=> playground: add wordwrap control

.changeset/spotty-spoons-compete.md, packages/preset-base/src/conditions.ts, packages/studio/styled-system/types/conditions.d.ts
The `_indeterminate` condition causes a syntax error due to a missing square bracket.
```
<css input> Unclosed bracket
21 |     }
22 |     .indeterminate\:bg_alias\.bg\.brand\.default {
> 23 |         &:is(:indeterminate, [data-indeterminate], [aria-checked=mixed], [data-state="indeterminate") {
|             ^
24 |             background-color: var(--colors-alias-bg-brand-default)
25 |         }
```
No Unclosed Bracket error. 😄 
No
=> fix(preset): a missing bracket in _indeterminate condition

playground/src/hooks/usePanda.ts
Revert order
**Before**:
**After**:
=> fix: playground tabs order

.changeset/moody-schools-live.md, packages/postcss/src/index.ts
Closes https://github.com/chakra-ui/panda/issues/1827
Fix a regression with the @pandacss/astro integration where the automatically provided `base.css` would be ignored by
the @pandacss/postcss plugin
no
=> fix: allow @pandacss/astro/base.css in postcss plugin

.changeset/odd-pumas-try.md, packages/node/src/builder.ts
Fix an issue with the postcss plugin when a config change sometimes didn't trigger files extraction
no
=> fix(postcss): config change sometimes didnt trigger files extraction

.changeset/serious-llamas-play.md, packages/parser/__tests__/output.test.ts, packages/parser/src/parser.ts
Closes https://github.com/chakra-ui/panda/issues/1801
Fix a parser issue where we didn't handle import aliases when using a {xxx}.raw() function.
ex:
```ts
// button.stories.ts
import { button as buttonRecipe } from '@ui/styled-system/recipes'
export const Primary: Story = {
// ❌ this wouldn't be parsed as a recipe because of the alias + .raw()
//  -> ✅ it's now fixed
args: buttonRecipe.raw({
color: 'primary',
}),
}
```
=> fix(parser): handle {xxx}.raw aliasing

.changeset/pretty-hounds-smell.md, packages/core/src/stylesheet.ts, packages/parser/__tests__/output.test.ts
Automatically extract/generate CSS for `sva` even if `slots` are not statically extractable, since it will only produce
atomic styles, we don't care much about slots for `sva` specifically
Currently the CSS won't be generated if the `slots` are missing which can be problematic when getting them from another
file, such as when using `Ark-UI` like `import { comboboxAnatomy } from '@ark-ui/anatomy'`
```ts
import { sva } from '../styled-system/css'
import { slots } from './slots'
const card = sva({
slots, // ❌ did NOT work -> ✅ will now work as expected
base: {
root: {
p: '6',
m: '4',
w: 'md',
boxShadow: 'md',
borderRadius: 'md',
_dark: { bg: '#262626', color: 'white' },
},
content: {
textStyle: 'lg',
},
title: {
textStyle: 'xl',
fontWeight: 'semibold',
pb: '2',
},
},
})
```
no
=> feat(sva): automatically generate CSS for sva with unresolved slots

.changeset/silver-cherries-walk.md, packages/generator/src/parser-options.ts, packages/parser/__tests__/css-raw.test.ts, packages/parser/__tests__/fixture.ts, packages/parser/__tests__/output.test.ts, packages/parser/__tests__/string-literal.test.ts, packages/parser/src/parser.ts, sandbox/astro/src/components/Card.astro, sandbox/astro/src/pages/index.astro
Closes  https://github.com/chakra-ui/panda/issues/1800
Fix & perf improvement: skip JSX parsing when not using `config.jsxFramework` / skip tagged template literal parsing
when not using `config.syntax` set to "template-literal"
no
=> perf(parser): skip jsx/template literal syntax parsing if disabled

website/pages/docs/concepts/recipes.md
It appears that config recipes can be applied responsively, while CVA recipes cannot. To make a button large/small based on a media query with a CVA recipe, the responsiveness would either need to be part of the recipe itself, or you would need to show/hide two separate buttons based on a media query.
=> docs: Update recipes.md to include comparison of responsive styling

packages/astro-plugin-studio/package.json, packages/astro/package.json, packages/config/package.json, packages/core/package.json, packages/error/package.json, packages/extractor/package.json, packages/generator/package.json, packages/is-valid-prop/package.json, packages/logger/package.json, packages/node/package.json, packages/parser/package.json, packages/postcss/package.json, packages/preset-atlaskit/package.json, packages/preset-base/package.json, packages/preset-open-props/package.json, packages/preset-panda/package.json, packages/shared/package.json, packages/studio/package.json, packages/token-dictionary/package.json, packages/types/package.json
This change is a must-have for Renovate support added in renovatebot/renovate#26306 as it [compares](https://docs.renovatebot.com/presets-monorepo/#monorepopanda-css) URLs in package.json
> Monorepo branch:
> Another branch:
> Missing source:
=> chore: add package metadata

website/pages/docs/installation/vue.mdx
Change Syntax Highlighting for [installation/vue page](https://panda-css.com/docs/installation/vue#start-using-panda)
Change `md` to `vue-html`
The highlighting will be different when set to `vue` and when set to `vue-html`. 
`vue-html` doesn't allow `import` syntax, and the `css` method calls in `vue` are different from `vetur` highlighting. 
> changed to `vue` case
I personally think the `css` method calls are important, so I set it to `vue-html`, and I think it's more readable than the previous version with no highlighting at all.
=> docs: md format to vue

playground/src/hooks/useConfig.ts
Playground: reset errors when code wuthout preset becomes valid
=> Playground: reset errors when code wuthout preset becomes valid

.changeset/short-files-exist.md, packages/generator/src/generator.ts, packages/node/src/builder.ts
Closes https://github.com/chakra-ui/panda/issues/1897
- Fix an issue with the `@pandacss/postcss` (and therefore `@pandacss/astro`) where the initial @layer CSS wasn't
applied correctly
- Fix an issue with `staticCss` where it was only generated when it was included in the config (we can generate it
through the config recipes)
no
=> fix: builder initial css + static

.changeset/loud-jokes-teach.md, packages/cli/src/cli-main.ts
Closes https://github.com/chakra-ui/panda/issues/1909
Fix an issue with the `panda init` command which didn't update existing `.gitignore` to include the `styled-system`
no
=> fix(cli): init with existing gitignore

.changeset/eighty-months-give.md, packages/core/__tests__/rule-processor.test.ts, packages/core/__tests__/style-decoder.test.ts, packages/core/__tests__/style-encoder.test.ts, packages/core/src/style-decoder.ts, packages/shared/src/css-important.ts, packages/types/src/style-rules.ts
Fix a regression with utility where boolean values would be treated as a string, resulting in "false" being seen as a
truthy value
no
=> fix(utilities): boolean value parsing

.changeset/neat-pianos-cry.md, .changeset/soft-snails-smile.md, packages/core/__tests__/serialize.test.ts, packages/core/__tests__/style-decoder.test.ts, packages/core/__tests__/style-encoder.test.ts, packages/core/src/utility.ts, packages/parser/__tests__/output.test.ts, packages/parser/src/parser-result.ts, packages/token-dictionary/src/create-dictionary.ts, packages/token-dictionary/src/utils.ts
Closes #1934
Closes #1928 
Support token reference syntax when authoring styles object, text styles and layer styles.
```jsx
const styles = css({
border: '2px solid {colors.primary}',
})
```
This will resolve the token reference and convert it to css variables.
```css
.border_2px_solid_\{colors\.primary\} {
border: 2px solid var(--colors-primary);
}
```
The alternative to this was to use the `token(...)` css function which will be resolved.
Both approaches return the css variable
```jsx
const styles = css({
// token reference syntax
border: '2px solid {colors.primary}',
// token function syntax
border: '2px solid token(colors.primary)',
})
```
However, The `token(...)` syntax allows you to set a fallback value.
```jsx
const styles = css({
border: …
```
=> feat: resolve token reference everywhere

.changeset/breezy-cars-rescue.md, packages/preset-base/src/conditions.ts, packages/studio/styled-system/types/conditions.d.ts, website/pages/docs/concepts/conditional-styles.md
Adds condition data-placeholder, data-placeholder-shown.
used on zagjs, ark-ui, radix and in react-aria widely. would be nice to support that.
Placeholder condition only targets native placeholder selector
Placeholder condition additionally targets data-placeholder and data-placeholder shown conditions
No.
=> feat(preset-base): add data-placeholder, data-placeholder-shown condition

.changeset/pretty-geese-cry.md, packages/core/src/stylesheet.ts
Closes https://github.com/chakra-ui/panda/discussions/1920
Display better CssSyntaxError logs
```
🐼 error [sheet:toCss] <css input>:2:20: Missed semicolon
🐼 error [sheet:toCss] Line 2:20, in:
🐼 error [sheet:toCss] .bg_111\:\:green\.600 {
background: 111::green.600
}
```
```
🐼 error [sheet:toCss]   1 | .bg_111\:\:green\.600 {
> 2 |     background: 111::green.600
|                    ^
3 | }
```
it's colored now
=> chore(logs): use CssSyntaxError showSourceCode method

.changeset/khaki-beds-sip.md, packages/generator/__tests__/generate-prop-types.test.ts, packages/generator/src/artifacts/types/prop-types.ts, website/pages/docs/concepts/writing-styles.md, website/pages/docs/references/config.md
follow-up of https://github.com/chakra-ui/panda/commit/a179d74fb3f9e36a036a939c57725556b05c6d63
add docs for strictPropertyValues & a few more examples for strictTokens
includes a fix for the strictToken option, since there was no release since the last PR I didnt include a changeset on this one
=> fix: strict tokens + docs for strictPropertyValues

website/pages/docs/utilities/layout.md
The accepted values for the aspectRatio property seem to have changed since the doc was written.
I can't see the properties listed by the documentation when autocompleting the available values in VS Code.
I replace the old values with the new one.
No
=> docs: update the accepted values for aspectRatio property

.changeset/yellow-foxes-hope.md, packages/config/src/get-mod-deps.ts
Change the config dependencies (files that are transitively imported) detection a bit more permissive to make it work by
default in more scenarios.
This helps when you're in a monorepo and you have a workspace package for your preset, and you want to see the HMR
reflecting changes in your app.
Currently, we only traverse files with the `.ts` extension, this change makes it traverse all files ending with `.ts`,
meaning that it will also traverse `.d.ts`, `.d.mts`, `.mts`, etc.
```ts
// apps/storybook/panda.config.ts
import preset from '@acme/preset'
// ...
})
```
This would not work before, but now it does.
```jsonc
{
"name": "@acme/preset",
"types": "./dist/index.d.mts", // we only looked into `.ts` files, so we …
```
=> fix(postcss): auto-resolve config dependencies from `.d.ts` files

.changeset/late-weeks-tickle.md, packages/node/src/setup-config.ts
Fix `prettier` parser warning in panda config setup
**Before:**
**After:**
=> Fix: `prettier` parser warning in panda config setup

playground/src/hooks/usePanda.ts, playground/src/hooks/usePandaContext.ts
sometimes the playground crashes for seemingly random reasons, let's future proof it with some try/catch
one of the reasons it happens is when there's a CSS syntax error and this `showSourceCode` gets called
https://github.com/chakra-ui/panda/blob/fix/playground-crash/packages/core/src/stylesheet.ts#L34
which then tries to do nodejs specific stuff apparently
https://github.com/postcss/postcss/blob/763d57b78a57b7abb6aaf745ab046ad9380cca9c/lib/css-syntax-error.js#L55-L57
=> fix: playground crashing when there's an error

website/pages/docs/customization/config-functions.md
should mirror the same format as in the theme.extend.keyframes
closes https://github.com/chakra-ui/panda/issues/2027
=> fix(docs): defineKeyframes usage

.changeset/heavy-sheep-accept.md, packages/core/__tests__/import-map.test.ts, packages/core/src/file-matcher.ts, packages/core/src/import-map.ts, packages/node/src/config.ts, packages/node/src/diff-engine.ts, packages/node/src/load-tsconfig.ts, packages/types/src/config.ts, sandbox/codegen/__tests__/styled-factory.test.tsx, website/pages/docs/overview/faq.md
Closes #2025
Closes #2011
Fix the issue where HMR doesn't work when config paths are used.
- On the first load, the tsconfig is loaded and added to the context
- On HMR, the tsconfig result is not assigned (resulting in `undefined`). I don't know how this even worked before.
- Path comparison in the import map logic didn't work as expected.
HMR and Path comparison works as expected
=> fix: tsconfig paths and HMR

.changeset/strong-pans-hammer.md, packages/core/__tests__/rule-processor.test.ts, packages/core/src/stylesheet.ts
Closes https://github.com/chakra-ui/panda/issues/2033
Fix a regression with rule insertion order after triggering HMR that re-uses some CSS already generated in previous
triggers, introduced in v0.27.0
no
Internal details: we used to sort in the StyleDecoder only, and that lead to `this.atomic` sometimes not being fully sorted when generating the CSS: since it’s a Set, if an item was already there it would not be added again and this could mess with the order
=> fix: sort rules right before generating the CSS

.changeset/two-plants-jump.md, packages/core/src/breakpoints.ts, packages/core/src/patterns.ts, packages/core/src/recipes.ts
Slight perf improvement by caching a few computed properties that contains a loop
no
=> perf: cache computed properties with loops

.changeset/cuddly-poems-sort.md, packages/core/__tests__/custom-utility.test.ts, packages/core/src/utility.ts
Closes #2064
Fix the issue in the utility configuration where shorthand without `className` returns incorrect CSS when using the shorthand version.
Doesn't work
We gracefully set the className fallback to the shorthand
No
=> fix: utility shorthand

.changeset/large-suits-notice.md, packages/shared/__tests__/arbitrary-value.test.ts, packages/shared/src/arbitrary-value.ts
Refactor getArbitraryValue function to handle empty and non-string values properly
=> fix: getArbitraryValue function to handle empty and non-string values properly

.changeset/healthy-insects-travel.md, packages/core/__tests__/global-css.test.ts, packages/core/src/serialize.ts, packages/core/src/stringify.ts
Fix a regression (introduced in v0.26.2) with globalCss selector order
```ts
{
globalCss: {
html: {
".aaa": {
color: "red.100",
".bbb": {
color: "red.200",
".ccc": {
color: "red.300"
}
}
}
},
}
}
```
would incorrectly generate (regression introduced in v0.26.2)
```css
.aaa html {
color: var(--colors-red-100);
}
.bbb .aaa html {
color: var(--colors-red-200);
}
.ccc .bbb .aaa html {
color: var(--colors-red-300);
}
```
will now correctly generate again:
```css
.aaa html {
color: var(--colors-red-100);
}
.aaa html .bbb {
color: var(--colors-red-200);
}
.aaa html .bbb .ccc {
color: var(--colors-red-300);
}
```
a temporary workaround is to manually specify the `&` character like so:
```ts
{
globalCss: {
html: {
".aaa": {
color: "red.100",
"& .bbb": {
color: "red.200",
"& .ccc": {
color: …
```
=> fix: global css selector order

website/pages/docs/concepts/extend.md, website/pages/docs/customization/conditions.mdx, website/pages/docs/customization/patterns.mdx, website/pages/docs/customization/presets.md, website/pages/docs/customization/theme.mdx, website/pages/docs/customization/utilities.mdx
> Fixes several broken links to the minimal setup page in the documentation.
> When you follow the link in the text "If you want to use Panda with the bare minimum, without any of the defaults, you can read more about it here", a 404 error occurs.
> The link leads to the corresponding documentation page.
> No
=> docs: fixes several broken links to the minimal setup page

.changeset/friendly-wolves-fix.md, packages/core/src/color-mix.ts, packages/node/src/setup-config.ts
Fix an issue (introduced in v0.29) with `panda init` and add an assert on the new `colorMix` utility function
no
=> fix: 0.29 issue with panda init & color mix on object values

.changeset/cuddly-pianos-vanish.md, packages/node/package.json, packages/node/src/cpu-profile.ts, pnpm-lock.yaml
Closes [# ](https://github.com/chakra-ui/panda/discussions/2138)
Refactor the `--cpu-prof` profiler to use the `node:inspector` instead of relying on an external module
(`v8-profiler-next`, which required `node-gyp`)
no
=> refactor: use node:inspector for profiling

.changeset/perfect-rats-act.md, packages/config/__tests__/bundle-config.test.ts, packages/config/package.json, pnpm-lock.yaml
Closes #2144
Fix the regression caused by the downstream `bundle-n-require` package, which tries to load custom conditions first.
=> fix: config resolve regression

.changeset/strange-beds-fly.md, packages/core/__tests__/file-matcher.test.ts, packages/core/src/file-matcher.ts, packages/parser/__tests__/output.test.ts, packages/parser/src/parser.ts, packages/parser/src/project.ts, packages/types/src/hooks.ts
Closes https://github.com/chakra-ui/panda/discussions/2132
Allow configuring the `matchTag` / `matchTagProp` functions to customize the way Panda extracts your JSX. This can be
especially useful when working with libraries that have properties that look like CSS properties but are not and should
be ignored.
```tsx
// Here, the `position` property will be extracted because `position` is a valid CSS property
<Select.Content position="popper" sideOffset={5}>
```
```tsx
// ...
hooks: {
'parser:before': (args) => {
args.configure({
// ignore the Select.Content entirely
matchTag: (tag) => tag !== 'Select.Content',
// ...or specifically ignore the `position` property
matchTagProp: (tag, prop) => tag === 'Select.Content' && prop !== 'position',
})
},
},
})
```
no
=> feat(hooks): allow configuring the matchTag/matchTagProp extractor fns

.changeset/shy-carrots-teach.md, packages/generator/src/artifacts/solid-jsx/jsx.ts
Closes #2156
Fix the issue where styled factory in Solid.js could result in `Maximum call stack exceeded` when composing with another
libraries that use the `as` prop.
This was related to how we split props within the factory. The previous approach could lead to extraneous props like "as" being passed to the underlying component.
=> fix: solid jsx factory

.changeset/three-squids-approve.md, packages/cli/src/cli-main.ts
Closes https://github.com/chakra-ui/panda/issues/2166
This fix adds the missing outdir param that goes with the `--outdir` flag of the `panda studio` command.
The command `panda studio --build --outdir my-folder`
throws this error :
```
🐼 error [cli] TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received type boolean (true)
at new NodeError (node:internal/errors:406:5)
at validateString (node:internal/validators:162:11)
at resolve (node:path:1101:7)
at CAC.<anonymous> (/Users/julienglorieux/Dev/cocolis-front/apps/web/node_modules/@pandacss/dev/dist/cli-default.js:18741:40)
at async main (/Users/julienglorieux/Dev/cocolis-front/apps/web/node_modules/@pandacss/dev/dist/cli-default.js:18914:5)
```
This builds with the param as the output.
No
=> fix(cli): missing outdir param for studio

packages/generator/__tests__/generate-reset.test.ts, packages/generator/src/artifacts/css/reset-css.ts
As the title says.
Basically no effect.
body already has line-height applied with `* { font: inherit }`.
~~If there was a problem before, when we defined the `scope` of `preflight`,  
it would deviate from the scope and rewrite the style of the body.~~
(According to the test results, this is incorrect🙈)
body `lign-height` will not be set.
~~Maybe~~ No
—
=> ♻️ Remove unnecessary body line-height

.changeset/shiny-fans-cry.md, packages/generator/src/artifacts/preact-jsx/jsx.ts, packages/generator/src/artifacts/qwik-jsx/jsx.ts, packages/generator/src/artifacts/react-jsx/jsx.ts, packages/generator/src/artifacts/solid-jsx/jsx.ts, packages/generator/src/artifacts/vue-jsx/jsx.ts, packages/studio/styled-system/jsx/factory.mjs, sandbox/codegen/__tests__/frameworks/preact.styled-factory.test.tsx, sandbox/codegen/__tests__/frameworks/qwik.styled-factory.test.tsx, sandbox/codegen/__tests__/frameworks/solid.styled-factory.test.tsx, sandbox/codegen/__tests__/frameworks/vue.styled-factory.test.tsx
Fix `styled` factory nested composition with `cva`
```ts
const Button = styled("button", { ... });
const PageButton = styled(Button, { ... }); // this was correctly merging the styles from Button+PageButton 
const SectionButton = styled(PageButton, { ... }); // this was not merging the styles from Button+PageButton+SectionButton correctly
```
somewhat, this worked fine for the 1st merging but not afterwards, it works as expected now
=> fix: styled nested composition with cva

packages/extractor/__tests__/extract.test.ts, packages/extractor/__tests__/unbox.test.ts, packages/extractor/src/unbox.ts, packages/extractor/src/utils.ts
when a "0" was used in a condition, the static analysis did not generate the associated CSS
repro here : https://play.panda-css.com/DM54SPp9HR
turns out to be a bug in the `unbox` function which ignores all falsy values
No
=> fix: unboxing of 0 values in conditionals

.changeset/wild-balloons-kneel.md, packages/core/__tests__/atomic-rule.test.ts, packages/core/__tests__/breakpoints.test.ts, packages/core/__tests__/complex-rule.test.ts, packages/core/__tests__/composition.test.ts, packages/core/__tests__/conditions.test.ts, packages/core/__tests__/global-css.test.ts, packages/core/__tests__/prefix.test.ts, packages/core/__tests__/recipe-nesting.test.ts, packages/core/__tests__/recipe.test.ts, packages/core/__tests__/rule-processor.test.ts, packages/core/__tests__/sort-style-rules.test.ts, packages/core/__tests__/static-css.test.ts, packages/core/__tests__/style-decoder.test.ts, packages/core/src/breakpoints.ts, packages/core/src/conditions.ts, packages/generator/__tests__/generate-token.test.ts, packages/parser/__tests__/import-map.test.ts, packages/parser/__tests__/output.test.ts, packages/parser/__tests__/preset-patterns.test.ts, packages/studio/styled-system/types/conditions.d.ts
Closes #2209
Switch from `em` to `rem` for breakpoints and container queries to prevent side effects.  `rem` units are often preferred due to their scalability, predictability, and ease of maintenance in complex layouts.
The `em` is relative to the parent's font size and can have side effects when used in container queries.
`rem` is more consistent and recommended. [Learn more](https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/#media-queries-7)
No
=> feat: use `rem` for media and container queries

packages/logger/src/index.ts
so that the `@pandacss/logger` and `@pandacss/token-dictionary` are not dependent on `process`
=> fix: logger process check

.changeset/mean-flies-tan.md, packages/shared/__tests__/property-priority.test.ts, packages/shared/src/shorthand-properties.ts
Always sort `all` to be first, so that other properties can easily override it
no
=> fix: always generate `all` CSS rules before the others

.changeset/shiny-eagles-love.md, packages/core/__tests__/file-matcher.test.ts, packages/core/src/file-matcher.ts, packages/parser/__tests__/output.test.ts, packages/parser/src/parser.ts
- Prevent extracting style props of `styled` when not explicitly imported
- Allow using multiple aliases for the same identifier for the `/css` entrypoints just like `/patterns` and `/recipes`
```ts
import { css as css2 } from '../styled-system/css'
css({ display: 'flex' })
css2({ flexDirection: 'column' }) // this wasn't working before, now it does
```
as long as you're importing the `styled` factory, it shouldnt matter
=> fix: allow multiple aliases from /css entrypoint

.changeset/curvy-doors-protect.md, packages/config/src/validation/validate-condition.ts, packages/core/__tests__/conditions.test.ts, packages/core/__tests__/global-css.test.ts, packages/core/__tests__/rule-processor.test.ts, packages/core/__tests__/style-decoder.test.ts, packages/core/__tests__/style-encoder.test.ts, packages/core/src/breakpoints.ts, packages/core/src/conditions.ts, packages/core/src/parse-condition.ts, packages/core/src/sort-style-rules.ts, packages/core/src/style-decoder.ts, packages/generator/src/artifacts/css/token-css.ts, packages/generator/src/artifacts/js/conditions.ts, packages/parser/__tests__/output.test.ts, packages/types/src/conditions.ts, packages/types/src/style-rules.ts, sandbox/preact-ts/panda.config.ts, sandbox/preact-ts/src/app.tsx
Closes https://github.com/chakra-ui/panda/discussions/1216
Add a way to create config conditions with nested at-rules/selectors
```ts
export default defaultConfig({
conditions: {
extend: {
supportHover: ['@media (hover: hover) and (pointer: fine)', '&:hover'],
},
},
})
```
```ts
css({
_supportHover: {
color: 'red',
},
})
```
will generate the following CSS:
```css
@media (hover: hover) and (pointer: fine) {
&:hover {
color: red;
}
}
```
no
=> feat: mixed conditions

.changeset/light-worms-dress.md, packages/parser/__tests__/output.test.ts, packages/token-dictionary/__tests__/color-palette.test.ts, packages/token-dictionary/src/dictionary.ts, packages/token-dictionary/src/middleware.ts
Using colorPalette with DEFAULT values will now also override the current token path
Given this config:
```ts
// ...
theme: {
extend: {
colors: {
bg: {
primary: {
DEFAULT: {
value: '{colors.red.500}',
},
base: {
value: '{colors.green.500}',
},
hover: {
value: '{colors.yellow.300}',
},
},
},
},
},
},
},
})
```
And this style usage:
```ts
import { css } from 'styled-system/css'
css({
colorPalette: 'bg.primary',
})
```
This is the difference in the generated css
```diff
@layer utilities {
.color-palette_bg\\.primary {
+    --colors-color-palette: var(--colors-bg-primary);
--colors-color-palette-base: var(--colors-bg-primary-base);
--colors-color-palette-hover: var(--colors-bg-primary-hover);
}
}
``` …
=> fix: colorPalette with DEFAULT values should include self

.changeset/friendly-eggs-live.md, packages/cli/src/cli-main.ts, packages/node/src/cpu-profile.ts
Allow dynamically recording profiling session by pressing the `p` key in your terminal when using the `--cpu-prof` flag
for long-running sessions (with `-w` or `--watch` for `panda` / `panda cssgen` / `panda codegen`).
no
mostly useful for [performance profling](https://panda-css.com/docs/guides/debugging#performance-profiling) as a maintainer
=> feat(cli): profiler shortcuts, type `p` to start/stop when watching

website/pages/docs/installation/nuxt.mdx
The setup guide for Nuxt doesn't mention adding `app.vue` to `includes`. If one just carelessly copies the example (like me), then styles will work, except in `app.vue`. Since `app.vue` is a default Nuxt file, it should be included.
No
=> docs(nuxt): add app.vue as default file for config example

.changeset/witty-pans-add.md, packages/generator/__tests__/generate-reset.test.ts, packages/generator/src/artifacts/css/reset-css.ts, packages/types/src/config.ts
Closes #1992
Add support for element level css reset via `preflight.level`. Learn more [here](https://github.com/chakra-ui/panda/discussions/1992).
Setting `preflight.level` to `'element'` applies the reset directly to the individual elements that have the scope class
assigned.
```js
preflight: {
scope: '.my-scope',
level: 'element', // 'element' | 'parent (default)'
},
// ...
})
```
This will generate CSS that looks like:
```css
button.my-scope {
}
img.my-scope {
}
```
This approach allows for more flexibility, enabling selective application of CSS resets either to an entire parent
container or to specific elements within a container.
No
=> feat: css reset scope

.changeset/bright-stingrays-drum.md, packages/core/__tests__/rule-processor.test.ts, packages/generator/__tests__/generate-token-js.test.ts, packages/token-dictionary/__tests__/color-palette.test.ts, packages/token-dictionary/src/dictionary.ts
Unify the token path syntax when using `formatTokenName`
Example with the following config:
```ts
hooks: {
'tokens:created': ({ configure }) => {
configure({
formatTokenName: (path: string[]) => '$' + path.join('-'),
})
},
},
})
```
Will now allow you to use the following syntax for token path:
```diff
- css({ boxShadow: '10px 10px 10px {colors.$primary}' })
+ css({ boxShadow: '10px 10px 10px {$colors-primary}' })
- token.var('colors.$primary')
+ token.var('$colors-black')
```
=> feat: use token.name instead of static `{category}.{prop}` syntax

.changeset/poor-lamps-look.md, packages/cli/src/index.ts, packages/config/src/config-deps.ts
Add `definePlugin` config functions for type-safety around plugins, add missing `plugins` in config dependencies to trigger a config reload on `plugins` change
=> feat: definePlugin & missing config-deps on `plugins` key

.changeset/wicked-crews-turn.md, packages/config/__tests__/validate-config.test.ts, packages/config/src/validation/validate-tokens.ts
Closes https://github.com/chakra-ui/panda/issues/2283 https://github.com/chakra-ui/panda/issues/2284
Fix "missing token" warning when using DEFAULT in tokens path
```ts
validation: 'error',
theme: {
colors: {
primary: {
DEFAULT: { value: '#ff3333' },
lighter: { value: '#ff6666' },
},
background: { value: '{colors.primary}' }, // <-- ⚠️ wrong warning
background2: { value: '{colors.primary.lighter}' }, // <-- no warning, correct
},
},
},
})
```
---
Add a warning when using `value` twice
```ts
validation: 'error',
theme: {
tokens: {
colors: {
primary: { value: '#ff3333' },
},
},
colors: {
primary: {
value: { …
```
=> fix: config validation with DEFAULT and nesting in value

packages/types/src/config.ts, website/pages/docs/references/config.md
The default value of preflight is probably written incorrectly.
"body" has a `margin` etc.  
https://stackblitz.com/edit/vitejs-vite-iltv13?file=panda.config.ts
<kbd> ![image](https://github.com/chakra-ui/panda/assets/13148112/f9e02610-7952-42ea-bfb8-5f8dfa8d5d5e)
If not set, `Preflight` will not be applied.  
The documentation should also be rewritten as such.
No
=> 🐛 Fix preflight default value 

.changeset/sixty-trains-mix.md, packages/generator/src/artifacts/js/is-valid-prop.ts, packages/studio/styled-system/jsx/is-valid-prop.d.ts
Fix `splitCssProps` typings, it would sometimes throw `Expression produces a union type that is too complex to represent"`
no
=> fix: splitCssProps typings

.changeset/neat-buttons-shout.md, packages/types/src/config.ts, website/pages/docs/overview/faq.md, website/pages/docs/references/config.md
Deprecates `emitPackage`, it will be removed in the next major version.
It's known for causing several issues:
- bundlers sometimes eagerly cache the `node_modules`, leading to `panda codegen` updates to the `styled-system` not
visible in the browser
- auto-imports are not suggested in your IDE.
- in some IDE the typings are not always reflected properly
- relative paths instead of absolute paths (e.g. `../styled-system/css` instead of `styled-system/css`)
- use [package.json #imports](https://nodejs.org/api/packages.html#subpath-imports) and/or tsconfig path aliases (prefer
package.json#imports when possible, TS 5.4 supports them by default) like `#styled-system/css` instead of
`styled-system/css`
- for a [component library](https://panda-css.com/docs/guides/component-library), use a …
=> chore: deprecates emitPackage

.changeset/curvy-bikes-peel.md, packages/core/__tests__/color-mix.test.ts, packages/generator/__tests__/generate-token.test.ts, packages/token-dictionary/__tests__/color-mix.test.ts, packages/token-dictionary/src/dictionary.ts, packages/token-dictionary/src/transform.ts
Closes https://github.com/chakra-ui/panda/discussions/2110#discussioncomment-8323928
Allow using the color opacity modifier syntax (`blue.300/70`) in token references:
- `{colors.blue.300/70}`
- `token(colors.blue.300/70)`
Note that this works both in style usage and in build-time config.
```ts
// runtime usage
css({ bg: '{colors.blue.300/70}' })
// => @layer utilities {
//    .bg_token\(colors\.blue\.300\/70\) {
//      background: color-mix(in srgb, var(--colors-blue-300) 70%, transparent);
//    }
//  }
css({ bg: 'token(colors.blue.300/70)' })
// => @layer utilities {
//    .bg_token\(colors\.blue\.300\/70\) {
//      background: color-mix(in srgb, var(--colors-blue-300) 70%, transparent);
//    }
//  }
```
```ts
// build-time usage
import { …
```
=> feat: color opacity modifier in token references (runtime & config)

.changeset/proud-dogs-flash.md, packages/astro-plugin-studio/CHANGELOG.md, packages/cli/CHANGELOG.md, packages/config/CHANGELOG.md, packages/core/CHANGELOG.md, packages/extractor/CHANGELOG.md, packages/fixture/CHANGELOG.md, packages/generator/CHANGELOG.md, packages/generator/__tests__/generate-token.test.ts, packages/logger/CHANGELOG.md, packages/node/CHANGELOG.md, packages/parser/CHANGELOG.md, packages/postcss/CHANGELOG.md, packages/preset-base/CHANGELOG.md, packages/preset-panda/CHANGELOG.md, packages/shared/CHANGELOG.md, packages/studio/CHANGELOG.md, packages/token-dictionary/CHANGELOG.md, packages/token-dictionary/src/transform.ts, packages/types/CHANGELOG.md
Closes https://github.com/chakra-ui/panda/issues/2318
Fix the color opacity modifier syntax for `semanticTokens` inside of conditions
```ts
conditions: {
light: '.light &',
dark: '.dark &',
},
theme: {
tokens: {
colors: {
blue: { 500: { value: 'blue' } },
green: { 500: { value: 'green' } },
},
opacity: {
half: { value: 0.5 },
},
},
colors: {
secondary: {
value: {
base: 'red',
_light: '{colors.blue.500/32}', // <-- wasn't working as expected
_dark: '{colors.green.500/half}',
},
},
},
},
},
})
```
will now correctly generate the following CSS:
```css
@layer tokens {
:where(:root, :host) {
--colors-blue-500: blue;
--colors-green-500: green;
--opacity-half: 0.5;
--colors-secondary: red;
}
.light { …
```
=> fix: color-mix in semanticTokens conditions

.changeset/orange-bikes-collect.md, packages/core/src/file-matcher.ts, packages/core/src/import-map.ts, packages/extractor/__tests__/extract.test.ts, packages/parser/__tests__/import.test.ts, packages/parser/__tests__/output.test.ts, packages/parser/src/get-import-declarations.ts
Allow using namespaced imports
```ts
import * as p from 'styled-system/patterns'
import * as recipes from 'styled-system/recipes'
import * as panda from 'styled-system/css'
// this will now be extracted
p.stack({ mt: '40px' })
recipes.cardStyle({ rounded: true })
panda.css({ color: 'red' })
panda.cva({ base: { color: 'blue' } })
panda.sva({ base: { root: { color: 'green' } } })
```
no
=> feat: extract namespace imports

.changeset/few-dragons-retire.md, packages/generator/src/artifacts/preact-jsx/jsx.string-literal.ts, packages/generator/src/artifacts/preact-jsx/jsx.ts, packages/generator/src/artifacts/qwik-jsx/jsx.string-literal.ts, packages/generator/src/artifacts/qwik-jsx/jsx.ts, packages/generator/src/artifacts/react-jsx/jsx.string-literal.ts, packages/generator/src/artifacts/react-jsx/jsx.ts, packages/studio/styled-system/jsx/factory.mjs, sandbox/codegen/__tests__/frameworks/preact.styled-factory.test.tsx, sandbox/codegen/__tests__/frameworks/qwik.styled-factory.test.tsx
Closes https://github.com/chakra-ui/panda/issues/2330
Fix nested `styled` factory composition
```tsx
import { styled } from '../styled-system/jsx'
const BasicBox = styled('div', { base: { fontSize: '10px' } })
const ExtendedBox1 = styled(BasicBox, { base: { fontSize: '20px' } })
const ExtendedBox2 = styled(ExtendedBox1, { base: { fontSize: '30px' } })
export const App = () => {
return (
<>
{/* ✅ fs_10px */}
<BasicBox>text1</BasicBox>
{/* ✅ fs_20px */}
<ExtendedBox1>text2</ExtendedBox1>
{/* BEFORE: ❌ fs_10px fs_30px */}
{/* NOW: ✅ fs_30px */}
<ExtendedBox2>text3</ExtendedBox2>
</>
)
}
```
follow up to https://github.com/chakra-ui/panda/pull/2192
=> fix: remove extraneous classes on nested styled composition

.changeset/slimy-bugs-double.md, packages/types/src/parser.ts
Add missing methods for ParserResultInterface (which can be used in the `parser:after` hook to dynamically add extraction results from your own logic, like using a custom parser)
no
(these are just types fixing, it was already ok at runtime)
=> fix: add missing ParserResultInterface typings

.changeset/rude-ravens-listen.md, packages/core/src/file-matcher.ts, packages/core/src/jsx.ts, packages/parser/__tests__/output.test.ts
Fix extraction of JSX `styled` factory when using namespace imports
```tsx
import * as pandaJsx from '../styled-system/jsx'
// ✅ this will work now
pandaJsx.styled('div', { base: { color: 'red' } })
const App = () => <pandaJsx.styled.span color="blue">Hello</pandaJsx.styled.span>
```
no
follow-up to https://github.com/chakra-ui/panda/pull/2327
=> fix(parser): JSX styled namespace imports

.changeset/many-tomatoes-sneeze.md, packages/generator/__tests__/generate-prop-types.test.ts, packages/generator/src/artifacts/types/prop-types.ts, packages/studio/styled-system/types/prop-type.d.ts, sandbox/codegen/__tests__/scenarios/strict-tokens.test.ts, sandbox/codegen/__tests__/scenarios/strict.test.ts
Allow using `!` or `!important` when using `strictTokens: true` (without TS throwing an error)
no
I found a way to get this working without losing type-safety and without polluting the suggestions with duplicates so we can get the best of both worlds !
=> feat: allow ! or !important with strictTokens

.changeset/five-phones-work.md, packages/token-dictionary/__tests__/color-mix.test.ts, packages/token-dictionary/src/transform.ts, sandbox/solid-ts/panda.config.ts
Closes # 
Fix an issue when using a semantic token with one (but not all) condition using the color opacity modifier
```ts
theme: {
extend: {
tokens: {
colors: {
black: { value: 'black' },
white: { value: 'white' },
},
},
colors: {
fg: {
value: {
base: '{colors.black/87}',
_dark: '{colors.white}', // <- this was causing a weird issue
},
},
},
},
},
},
})
```
Panda throws
now it doesn't 
no
=> fix: color opacity modifier with semanticTokens

.changeset/clever-coats-check.md, packages/config/__tests__/merge-config.test.ts, packages/config/src/get-resolved-config.ts, packages/config/src/merge-config.ts, packages/parser/__tests__/output.test.ts
Fix merging issue when using a preset that has a token with a conflicting value with another (or the user's config)
```ts
const userConfig = defineConfig({
presets: [
{
theme: {
extend: {
tokens: {
colors: {
black: { value: 'black' },
},
},
},
},
},
],
theme: {
tokens: {
extend: {
colors: {
black: {
0: { value: 'black' },
10: { value: 'black/10' },
20: { value: 'black/20' },
30: { value: 'black/30' },
},
},
},
},
},
})
```
When merged with the preset, the config would create nested tokens (`black.10`, `black.20`, `black.30`) inside of the
initially flat `black` token.
This would cause issues as the token engine stops diving deeper after encountering an object with a `value` property.
To fix this, we now automatically replace the flat `black` …
=> fix: merging flat and nested object on same key

.changeset/purple-olives-cheat.md, packages/generator/__tests__/generate-style-props.test.ts, packages/generator/src/artifacts/types/style-props.ts, packages/studio/styled-system/types/style-props.d.ts, sandbox/codegen/__tests__/scenarios/strict-property-values.test.ts, sandbox/codegen/__tests__/scenarios/strict.test.ts
Closes https://github.com/chakra-ui/panda/issues/2390
Fix `strictPropertyValues` typings should allow for `CssVars` (either predefined from `globalVars` or any custom CSS
variable)
```ts
// ...
strictPropertyValues: true,
globalVars: {
extend: {
'--some-color': 'red',
'--button-color': {
syntax: '<color>',
inherits: false,
initialValue: 'blue',
},
},
},
})
```
```ts
css({
// ❌ was not allowed before when `strictPropertyValues` was enabled
display: 'var(--button-color)', // ✅ will now be allowed/suggested
})
```
If no `globalVars` are defined, any `var(--*)` will be allowed
```ts
css({
// ✅ will be allowed
display: 'var(--xxx)',
})
```
no
=> fix: strictPropertyValues should still allow for CSS vars

.changeset/blue-wolves-sniff.md, packages/parser/__tests__/output.test.ts, packages/parser/src/parser.ts
Closes https://github.com/cschroeter/park-ui/issues/264
Fix JSX matching with recipes after introducing namespace imports
```ts
// ...
theme: {
extend: {
slotRecipes: {
tabs: {
className: 'tabs',
slots: ['root', 'list', 'trigger', 'content', 'indicator'],
base: {
root: {
display: 'flex',
// ...
},
},
},
},
},
},
})
```
```tsx
const App = () => {
return (
// ❌ this was not matched to the `tabs` slot recipe
// ✅ fixed with this PR
<Tabs.Root defaultValue="button">
<Tabs.List>
<Tabs.Trigger value="button">Button</Tabs.Trigger>
<Tabs.Trigger value="radio">Radio Group</Tabs.Trigger>
<Tabs.Trigger value="slider">Slider</Tabs.Trigger>
<Tabs.Indicator />
</Tabs.List>
</Tabs.Root>
)
}
```
We introduced a bug in …
=> fix: JSX matching with recipes after introducing namespace imports

website/pages/docs/overview/browser-support.md
Closes # 
This fixes url for link `CSS Cascade Layers` on https://panda-css.com/docs/overview/browser-support
n/a
n/a
n/a
=> docs: fix link to "CSS Cascade Layers" caniuse page

.changeset/heavy-badgers-try.md, packages/parser/__tests__/output.test.ts, packages/shared/src/deep-set.ts
Closes https://github.com/chakra-ui/panda/issues/2439
Fix a bug where some styles would be grouped together in the same rule, even if they were not related to each other.
This was caused by an object reference being re-used while setting a property deeply in the hashes decoding process,
leading to the mutation of a previous style object with additional properties.
=> fix(shared): create a new object in deepSet, avoid re-using the same reference

.changeset/yellow-pens-poke.md, packages/config/src/merge-hooks.ts, packages/core/__tests__/file-matcher.test.ts, packages/core/__tests__/import-map.test.ts, packages/core/src/file-matcher.ts, packages/core/src/import-map.ts, packages/parser/__tests__/import-map.test.ts, packages/parser/src/parser.ts, packages/parser/src/project.ts, packages/types/src/config.ts, packages/types/src/hooks.ts, sandbox/preact-ts/package.json, sandbox/preact-ts/panda.config.ts, sandbox/preact-ts/src/app.tsx
Allow multiple `importMap` (or multiple single import entrypoints if using the object format).
It can be useful to use a component library's `styled-system` while also using your own `styled-system` in your app.
```ts
importMap: ['@acme/styled-system', '@ui-lib/styled-system', 'styled-system'],
})
```
Now you can use any of the `@acme/styled-system`, `@ui-lib/styled-system` and `styled-system` import sources:
```ts
import { css } from '@acme/css'
import { css as uiCss } from '@ui-lib/styled-system/css'
import { css as appCss } from '@ui-lib/styled-system/css'
```
no
=> feat: multiple importMap

.changeset/hot-rivers-rescue.md, packages/studio/astro.config.mjs, packages/studio/src/components/colors.tsx, packages/studio/src/components/font-family.tsx, packages/studio/src/components/font-tokens.tsx, packages/studio/src/components/overview.tsx, packages/studio/src/components/semantic-color.tsx, packages/studio/src/components/sizes.tsx, packages/studio/src/components/text-styles.tsx, packages/studio/src/lib/use-color-docs.ts, packages/studio/src/pages/sizes.astro, packages/studio/src/pages/spacing.astro, packages/studio/styled-system/styles.css, packages/token-dictionary/src/dictionary.ts, packages/token-dictionary/src/index.ts
- Handle displaying values using the `[xxx]` escape-hatch syntax for `textStyles` in the studio
- Display an empty state when there's no token in a specific token page in the studio
no
- Add `deepResolveReference` in TokenDictionary, helpful to get the raw value from a semantic token by recursively traversing the token references.
- Added some exports in the `@pandacss/token-dictionary` package, mostly useful when building tooling around Panda (Prettier/ESLint/VSCode plugin etc)
=> fix(studio): display escape hatch values in textStyles

website/pages/docs/overview/faq.md
This PR removes outdated information about Opacity Modifiers.
It says they're not supported, but [this feature is actually supported](https://panda-css.com/docs/concepts/color-opacity-modifier).
The FAQ was also pointing to this discussion: https://github.com/chakra-ui/panda/discussions/862
=> docs(faq): remove outdated info about opacity modifiers

.changeset/fair-teachers-kiss.md, packages/node/src/debug.ts
Using `/` as a separator makes the `replaceAll` not work on windows due to `path.sep` being `\`.
This change makes `panda debug` work on windows.
Closes # 
`panda debug` fails if it tries to create debug files for files that are under a directory. This means that a file `src/foo/component.tsx` is renamed to `src\foo\component.css` instead of `src__foo__component.css`.
`panda debug` renames the files correctly under windows.
No
=> fix: build correct path for debug files on windows

.changeset/config.json, .changeset/loud-tips-heal.md, packages/core/__tests__/import-map.test.ts, packages/core/src/import-map.ts, packages/fixture/src/create-context.ts, packages/parser/__tests__/output.test.ts, website/pages/docs/guides/debugging.mdx
Fix Panda imports detection when using `tsconfig`.`baseUrl` with an outdir that starts with `./`.
Styles were missing due to absolute imports not seen as valid Panda imports when using an outdir that started with `./`
```ts
// app.tsx
import { styled } from "styled-system/jsx";
// tsconfig.json
{
compilerOptions: {
baseUrl: '.',
},
},
// panda.config.ts
{
outdir: './styled-system',
}
```
no
If some part of your CSS is still missing when using absolute imports:
This can happen when `tsconfig` (with `paths` or `baseUrl`) or with package.json [`#imports`](https://nodejs.org/api/packages.html#subpath-imports).
Panda tries to automatically infer and read the custom paths defined in `tsconfig.json` file. However, there might be scenarios that won't work.
To fix this add the `importMap` option …
=> fix: imports detection leading to missing CSS when using tsconfig baseUrl with prefixed outdir

website/pages/docs/guides/fonts.md
This cleans up the Fontsource guide a little and fixes the incorrect examples. Additionally, I recommend pushing developers to use variable fonts for more flexibility (and slowly educate it to new developers as the new norm which is also what Google Fonts is doing).
No
I also maintain Fontsource and was wondering if you wanted to remove the [Chakra UI guide](https://fontsource.org/docs/guides/angular) from the sidebar and want to replace that with PandaCSS? If I understand correctly, Chakra UI is no longer the focus, right? I can make that change for you if that is ideal.
=> docs: clean up fontsource guide

.changeset/lovely-islands-applaud.md, packages/generator/__tests__/generate-prop-types.test.ts, packages/generator/src/artifacts/types/prop-types.ts, packages/studio/styled-system/types/prop-type.d.ts, sandbox/codegen/cli.ts
Closes  #2526. I tried deno check with panda, and found the following error.
```
error: TS2724 [ERROR]: '"file:///D:/Repos/project/styled-system/types/conditions.d.mts"' has no exported member named 'Conditional'. Did you mean 'Condition'?
import type { Conditional } from './conditions.d.mts';
~~~~~~~~~~~
at file:///D:/Repos/project/styled-system/types/prop-type.d.mts:2:15
TS2339 [ERROR]: Property 'initialLetterAlign' does not exist on type 'CssProperties'.
initialLetterAlign?: ConditionalValue<CssProperties["initialLetterAlign"] | AnyString>
~~~~~~~~~~~~~~~~~~~~
at file:///D:/Repos/project/styled-system/types/style-props.d.mts:3041:54
```
Generated prop-type.d.mts imports `Conditional ` that does not exist.
Generated prop-type.d.mts imports `ConditionalValue` that exist.
I don't think …
=> fix: invalid import in generated source

website/pages/docs/installation/nextjs.mdx
> The previous command gave an error and I fix it
> An error message is displayed when using the current command.
> With this command, other users won't have any problem when installing nextjs with bun.
Yes
Source: [https://bun.sh/guides/ecosystem/nextjs](https://bun.sh/guides/ecosystem/nextjs)
=> Fix bun command to install NextJS

website/src/components/sections/css-in-js.tsx
Small adjustment to the `maxW` prop of the mapped features in `css-in-js.tsx` to fix the off-center alignment.
No
I didn't generate a changeset as I didn't feel it was warranted for such a minor adjustment.
=> Docs: Fix section alignment

website/pages/docs/theming/tokens.md
Closes #2533
The [Border Width](https://panda-css.com/docs/theming/tokens#border-widths) section contained a duplicate callout from the Radii section. This PR removes it.
=> Docs: Remove duplicate Radii callout

.changeset/fresh-eggs-kneel.md, packages/generator/__tests__/generate-prop-types.test.ts, packages/preset-base/src/utilities/layout.ts, packages/studio/styled-system/types/prop-type.d.ts
Inherit all possible float values for the `float` utility, allowing values such as `none` to be passed in.
Panda only allowed `start`, `end`, `left` and `right`. 
More css values!
No
=> fix: allow passing in inherited float values

.changeset/violet-birds-tie.md, packages/generator/__tests__/generate-css-fn.test.ts, packages/generator/src/artifacts/js/css-fn.ts, packages/studio/styled-system/css/css.d.ts, sandbox/codegen/__tests__/css.test.ts, sandbox/codegen/__tests__/scenarios/strict.test.ts
Fix `css.raw` typings after recent ([0.39.0](https://github.com/chakra-ui/panda/discussions/2560)) changes allowing
arrays of `SystemStyleObject`
no
=> fix: css.raw typings

website/src/components/sections/try-panda.tsx
[This comment](https://github.com/chakra-ui/panda/issues/2592#issuecomment-2109070488) made me realize there's a discrepancy between the homepage installation instructions and the docs installation instructions.
The /docs/installation pages contain this command:
```
npx panda init --postcss
```
But try-panda.tsx, rendered on the homepage, instructs:
```
npm run panda init -p
```
This change makes the homepage match the docs pages.
I've tried to follow the contributing guidelines but I may have messed up somehow, apologies in advance if so.
Also, I wasn't able to actually run the website locally, but the string change should be correct. Possibly I should run a build command or something before merging? Thanks in advance. Happy to make additional changes, thanks so much for everything this …
=> docs: Make homepage installation instructions match docs

.changeset/wild-schools-camp.md, packages/node/src/analyze-tokens.ts
Fix ` error [cli] TypeError: Converting circular structure to JSON` when running `panda analyze --json output.json`
no
=> fix: panda analyze --json file

.changeset/unlucky-humans-own.md, packages/core/__tests__/serialize.test.ts, packages/core/__tests__/static-css.test.ts, packages/parser/__tests__/output.test.ts, packages/parser/__tests__/preset-patterns.test.ts, packages/token-dictionary/__tests__/expand-references.test.ts, packages/token-dictionary/src/dictionary.ts, packages/token-dictionary/src/expand-token-references.ts
Allow nesting (string) token references in the fallback argument, fix an issue where using CSS var in the fallback argument would be mistakenly escaped
```ts
css({ color: "token(colors.red.300, token(colors.blue.500, yellow))" )}
// ❌ -> "var(--colors-red-300, token\\(colors\\.blue\\.500))"
css({ color: "token(colors.red.300, var(--some-var, var(--another-var, purple)))" )}
// ❌ -> "var(--colors-red-300, var\\(--some-var)))"
```
```ts
css({ color: "token(colors.red.300, token(colors.blue.500, yellow))" )}
// ✅ -> "var(--colors-red-300, var(--colors-blue-500, yellow))"
css({ color: "token(colors.red.300, var(--some-var, var(--another-var, purple)))" )}
// ✅ -> "var(--colors-red-300, var(--some-var, var(--another-var, purple)))"
```
no
=> feat: allow nesting string token ref / fix CSS var in string token ref fallback

website/pages/docs/utilities/spacing.md
In the [documentation](https://panda-css.com/docs/utilities/spacing#horizontal-and-vertical-padding), CSS Property in `px`, `paddingX`, `py` and `paddingY` was written as `padding-left` or `padding-top`, but in the implementation it was `padding-inline` or `padding-block`. 
In [`@pandacss/preset-base`](https://github.com/chakra-ui/panda/blob/ca2998718f94990305299dc4d07c0869ff32cef7/packages/preset-base/src/utilities/spacing.ts).
```ts
paddingBlock: {
className: 'py',
values: 'spacing',
group: 'Padding',
shorthand: ['py', 'paddingY'],
},
// some lines
paddingInline: {
className: 'px',
values: 'spacing',
group: 'Padding',
shorthand: ['paddingX', 'px'],
},
```
`px` and `paddingX` of CSS Property is `padding-left`.
`py` and `paddingY` of CSS Property is `padding-top`.
`px` and `paddingX` of …
=> docs: fix px and py CSS Property

.changeset/kind-kiwis-arrive.md, packages/core/src/file.ts, packages/generator/src/artifacts/js/is-valid-prop.ts, packages/generator/src/artifacts/preact-jsx/pattern.ts, packages/generator/src/artifacts/qwik-jsx/pattern.ts, packages/generator/src/artifacts/react-jsx/pattern.ts, packages/generator/src/artifacts/solid-jsx/pattern.ts, packages/generator/src/artifacts/types/generated.ts, packages/generator/src/artifacts/vue-jsx/pattern.ts, sandbox/codegen/__tests__/scenarios/jsx-minimal.test.tsx, sandbox/codegen/__tests__/scenarios/jsx-none.test.tsx
Closes #2632
This PR optimizes the code generated for JSX patterns when `jsxStyleProps=none.` We used to create a component in the render function; now, we only create one component, avoiding re-renders.
No
I had to reuse the `css` prop pattern to achieve this but I believe it's fine since there's no way to override this prop from the consuming side.
=> fix(patterns): rewrite codegen for `jsxStyleProps=none`

website/pages/docs/guides/component-library.md
Hello,
While reading the [document](https://panda-css.com/docs/guides/component-library), I noticed that a link was incorrectly connected, so I just added a slash.
`docs/customization/presets`
`/docs/customization/presets`
No
=> docs: fix a incorrect link

website/pages/docs/customization/config-functions.md
I found that the example for `defineLayerStyles` from the [docs](https://panda-css.com/docs/theming/layer-styles#defining-layer-styles) throws type errors.
No
N/A
=> docs: fix background shorthand in defineLayerStyles

.changeset/sharp-emus-crash.md, packages/core/src/style-encoder.ts, packages/extractor/__tests__/extract.test.ts, packages/parser/__tests__/sva.test.ts
Closes https://github.com/chakra-ui/panda/issues/2671
Fix an issue where spreading an identifier in a sva `slots` array would prevent expected CSS from being generated
```ts
import { sva } from 'styled-system/css'
const parts = ['positioner', 'content']
const card = sva({
slots: [...parts], // <- spreading here was causing the below CSS not to be generated, it's now fixed ✅
base: {
root: {
p: '6',
},
},
})
```
no
=> fix(sva): spreading in slots would prevent CSS from being generated

.changeset/pretty-cameras-exist.md, packages/core/__tests__/recipe.test.ts, packages/core/__tests__/slot-recipe.test.ts, packages/core/src/recipes.ts, packages/core/src/style-decoder.ts, packages/core/src/types.ts, packages/parser/__tests__/output.test.ts
Change recipes `className` to be optional, both for `recipes` and `slotRecipes`, with a fallback to its name.
```ts
import { defineConfig } from '@pandacss/core'
recipes: {
button: {
className: 'button', // 👈 was mandatory, is now optional
variants: {
size: {
sm: { padding: '2', borderRadius: 'sm' },
md: { padding: '4', borderRadius: 'md' },
},
},
},
},
})
```
no
=> feat(recipes): change className to be optional

website/pages/docs/concepts/patterns.mdx
It took me a while to figure out that Grid's `minChildWidth` parameter doesn't work if `columns` are defined. I figure it might help other people.
No information on the fact that the two are not compatible
Adds information about the fact that it doesn't work if columns are defined.
"(must not be used with `columns`)"
No
N/A
=> docs: Adds information about Grid's minChildWidth property

.changeset/tender-parents-sin.md, packages/core/__tests__/serialize.test.ts, packages/shared/src/deep-set.ts
Closes #2772
Fix issue where `divideY` and `divideColor` utilities, used together in a recipe, doesn't generate the correct css.
Only the last one of `divideY` or `divideColor` works
Works as expected
No
=> fix: divide utility merging

.changeset/ninety-cheetahs-count.md, packages/generator/__tests__/generate-token.test.ts, packages/token-dictionary/src/transform.ts
Closes #2782
Fix issue where shadow token with color opacity modifier produces incorrect css value
=> fix: token reference expansion

.changeset/fresh-dodos-return.md, packages/generator/__tests__/generate-prop-types.test.ts, packages/generator/src/artifacts/types/prop-types.ts, packages/studio/styled-system/types/prop-type.d.ts
This pull request is a follow-up pull request to #2466.
Make `WithEscapeHatch<T>` much more performant and typescript happy by updating the type signature of `WithImportant<T>` and `WithColorOpacityModifier<T>` to use *branded type* and *non-distributive conditional types*, while keeping such tokens valid and also not appearing in autocompletions to prevent them from polluting autocompletion result (which is the current behavior).
Current type signaure of `WithImportant<T>` and `WithColorOpacityModifier<T>` somehow makes typescript compiler unhappy and slows down both code autocompletion and linting.
New type signaure of `WithImportant<T>` and `WithColorOpacityModifier<T>` is much more performant. On using `svelte-check` in large codebase was taking over 3 minutes but now it takes under 4 …
=> refactor: make `WithEscapeHatch<T>` much more performant

website/theme/recipes/navbar.recipe.ts
Closes # 
Hi everyone, I noticed that the doc website's mobile menu button appears at the wrong breakpoint.
https://github.com/user-attachments/assets/2ffe15da-fa27-4f0d-9da9-d182a61dae22
https://github.com/user-attachments/assets/15ae0296-e2e0-4d72-93e7-4a1f5c944591
No
=> fix(website): adjust the mobile menu button appear breakpoint

packages/shared/src/classname.ts
Just a quick early return that probably won't occur too often
Css checks if value is important before checking if it is null
Css checks if value is important after checking for null
No
=> perf(shared): do not check if value is important before checking if it is null

packages/shared/src/unit-conversion.ts
There's no reason to recreate these regex inside the function body, as they're static.
No.
=> perf(shared): move regex creation outside of `getUnit` function body

packages/shared/src/merge-props.ts
There's no reason to filter through all objects before reducing. We can just return early if the value is falsy.
No
=> perf(shared): return early if obj is falsy, avoiding an additional traversal

packages/generator/src/artifacts/js/conditions.ts, packages/studio/styled-system/css/conditions.mjs, packages/studio/styled-system/helpers.mjs
More low-hanging fruit. Just moving the regex creation out of the function body.
No
=> perf(artifacts): do not construct the condition regex within `isCondition` function body

website/pages/docs/customization/presets.md
Preset has supported `globalFontface`.
This PR add that to document.
No Change
No Change
No
`globalFontface` is introduced in https://github.com/chakra-ui/panda/pull/2738
It appears to be already supported at that point.
=> docs: add `globalFontface` to preset

website/src/nextra/toc.tsx
Closes # 
Hi everyone, I noticed that part of the table of contents gets cut off due to insufficient sticky top spacing, so I adjusted `top: 16` to `top: 20`. Feel free to close this if it's unnecessary.
No
=> fix(website): adjust sticky-top of toc to prevent content being cut off

website/pages/docs/utilities/background.md
Related to: https://github.com/chakra-ui/panda/discussions/1656
Improved documentation for using bgGradient.
Usage of gradients is not intuitive since it doesn't work with `backgroundImage`. Better documentation needed.
Added documentation examples for using `bgGradient` based on tokens.
No
=> docs: add example for bgGradient based on tokens

website/src/components/feature-marquee.tsx
Closes # 
Hi everyone, I noticed that the `li` elements in `feature-marquee.tsx` were not placed within permitted parent elements, so I replaced them with `div` elements.
Feel free to close this if I missed somthing.
```html
<div class="rfm-child">
<li class="mx_2"> 
<div class="d_flex ai_center gap_4 flex-d_row">
<span class="ls_tight">Design Tokens</span>
<span>•</span>
</div>
</li>
</div>
```
```html
<div class="rfm-child">
<div class="mx_2"> 
<div class="d_flex ai_center gap_4 flex-d_row">
<span class="ls_tight">Design Tokens</span>
<span>•</span>
</div>
</div>
</div>
```
No
N/A
=> fix(website): prevent li within non-permitted parent elements

website/pages/docs/theming/text-styles.md
Changed the lineHeight value from '24' to '24px' in the body text style to make the examples more realistic.
The `lineHeight` is set to a unitless value of `24`, which may not accurately reflect real-world usage.
Although I’m not sure if this was the value originally intended by the author, I have changed it based on my assumption. It may be appropriate to adjust it to a more suitable value later.
No
=> docs: fix example value more realistic

website/pages/docs/utilities/effects.md
Fixed the utilities/effects page title from `Background` to `Effects`.
No Change
No Change
No
https://panda-css.com/docs/utilities/effects
=> docs: fix title of effects page

.changeset/fast-zebras-live.md, packages/postcss/__tests__/postcss.test.ts, packages/postcss/src/index.ts
Closes [#2916](https://github.com/chakra-ui/panda/discussions/2916)
Fixes postcss race condition because builder instance is singelton, and postcss plugin is async.
Reported in bug report.
Added `builderGuard` which allow only one plugin invocation to be run at a time, other invocations will wait. Tested on my instance.
=> fix(postcss): race condition on builder instance for simultaneous plugin invocations

website/pages/docs/references/cli.md
Closes # 
I found wrong link at cli emitTokensOnly and fixed it.
( I'm really enjoying this library, thanks for maintaining. )
The shortcut for config emitTokensOnly doesn't work correctly.
The shortcut for config emitTokensOnly works correctly.
https://github.com/user-attachments/assets/3914602c-d045-4fd2-960f-0511fb3ba142
No
=> docs: fix wrong config emitTokensOnly link at cli emitTokensOnly

website/pages/docs/references/cli.md
Closes # 
https://github.com/chakra-ui/panda/pull/2969#issuecomment-2466089602
Fixed additional incorrect links.
- outExtension
- jsxFramework
- strictTokens
The shortcut for config doesn't work correctly.
The shortcut for config works correctly.
No
The cli reference page no longer seems to have any incorrect links.
=> docs: fix wrong config link at cli reference

CHANGELOG.md
=> Changelog v0.48.1

.github/composite-actions/install/action.yml, .github/workflows/quality.yml, .github/workflows/release.yml
Closes # 
Updated the versions of actions in the workflow files, including `actions/setup-node` to `v4`, `actions/checkout` to `v4`, and `slackapi/slack-github-action` to `v2`, to ensure compatibility and leverage the latest features and fixes provided by these releases.
* The workflow currently uses an older version of `actions/setup-node` (e.g., v2 or v3), which may lack the latest updates or features available in the `v4` release.
* The workflow uses an older version of `actions/checkout` that may not include the improvements and optimizations available in the `v4` release.
* The workflow uses an older version of `slackapi/slack-github-action`, which may not include the updates and fixes provided in …
=> chore(.github): update action version in workflow files

website/pages/docs/utilities/tables.md
> Corrected the 'Border Spacing Y' example in the documentation. Changed `borderSpacingX` to `borderSpacingY` to accurately reflect the vertical border-spacing property of a table.
=> docs: fix typo issue

website/pages/docs/overview/faq.md
When importing an image, Vite only returns the URL. Because of this, to use an image as a `backgroundImage` it needs to be wrapped in `url()`
The code example from the docs doesn't work 😢
The new code example works 🥳
No
=> docs(faq): wrap image in `url()` in Vite imported image example

website/pages/docs/utilities/svg.md
SVG examples are using wrong tag at https://panda-css.com/docs/utilities/svg
Uses `<div />`
Uses `<svg />`
No
The IDE auto-formatted the props table but no visual changes were made
=> docs: fix svg example tag

website/pages/docs/concepts/recipes.md
Update the recipe documentation. In the limitations of recipe, docs were saying:
```
When you use the recipe in a custom component that is not a JSX component, Panda won't be able to track the usage of the recipe variants.
```
And in the example, `Random` is actually a proper JSX component. So ig it was about having the same name?
And added a single line description on what's changed in the example.
Documentation have vague/incorrect info
Documentation have more specific info with more details on the example used.
No
=> docs(concept-recipe): update recipes.md

.changeset/warm-turtles-behave.md, packages/generator/__tests__/generate-token.test.ts, packages/generator/src/artifacts/css/token-css.ts
Closes #3250 
This PR fixes an issue where if one theme's name shared the start of another, both would be included in the resulting token generation. Example, if there was a `primary` theme and a `primary-legacy` theme, and we only wanted to generate `staticCss` for the `primary` theme, `primary-legacy` was also being included in the token generation due to it also started with `primary`
The current behavior checks to see if a theme should be skipped by checking if the key starts with any condition, this can overmatch in the example above
The new behavior is a bit more strict in its key matching. It looks for either an exact match on the condition or checks to see if condition starts with the key + a `:` so that conditions like dark mode still get generated.
This should not break any …
=> fix: theme skipping not skipping a theme if its name also starts with another theme name

.changeset/plenty-kings-collect.md, packages/core/src/import-map.ts
The default `cwd` option is `process.cwd()` and it uses Windows path separators, but there is code that uses the unix path separator for string matching.
Some import declarations are not detected if you use tsconfig path aliases.
The import declarations are detected and the result of parser is not empty.
No.
A temporary workaround could be:
```ts
// panda.config.ts
cwd: process.cwd().toString().replaceAll("\\", "/")
});
```
=> fix: normalize path separators

.changeset/young-cats-develop.md, packages/generator/__tests__/generate-token.test.ts, packages/token-dictionary/src/utils.ts
Closes #3275
Fix issue where `borderWidth` token reference adds an extra `px` to the generated css value
=> fix: border token reference

website/pages/docs/overview/faq.md
Adds a missing comma in the first code listing on the FAQ page (https://panda-css.com/docs/overview/faq) and changes to quotes from double quotes to single quotes.
Current example code is incorrect and contains a mix of single quotes and double quotes.
Updated example code is correct and contains only single quotes.
No.
=> Add missing comma in code listing in FAQs

.gitignore, package.json
Fixed an issue where Panda Studio could not be accessed.  
This was likely due to outdated directory structure changes in Panda Studio.
After running `pnpm build-studio && pnpm serve-studio`,  
accessing http://localhost:3000/ shows a `404` error
Panda Studio is displayed.
No
Related changes (probably):
1. [`const outDir = ..., 'panda-static')`](https://github.com/chakra-ui/panda/pull/15/files#diff-fa0bbb9e69ed035ce0715fe34ac3bdeb9e0f7156e2b0dda9a7ab2944e732ccc5)
1. [serve-docs](https://github.com/chakra-ui/panda/commit/ad89fdf7e11f842d4d036b4f72bdd5ea5b903f2b)
1. [CoreContext: `this.studio = { outdir: `${config.outdir}-studio`, ...`](https://github.com/chakra-ui/panda/pull/1860/files#diff-8cdff7aebde349d2e609762456a1ba82d73245df741ed73f8c86e517ccaff800R78)
=> fix(studio): fix CLI outdir

website/pages/docs/migration/styled-components.md
Noticed a small typo in the docs where the `styled` helper is invoked in a way that returns an JSX element rather than a component.
`styled.button({})` returns a JSX element, not a component, and is intended to be used directly in JSX, e.g. `<styled.button />`
`styled('button', {})` returns a `StyledComponent` instance which is the intended behavior here.
No, docs-only change -- and it's described correctly earlier on the same page ([here](https://panda-css.com/docs/migration/styled-components#object-syntax))
Thank you!
=> fix: update object literal syntax in styled components migration docs

website/pages/docs/installation/rsbuild.mdx
In yesterday PR i had small typo for highlighted command, fixed here
No
=> docs: rsbuid installation hotfix for highlight
