- README.md
- website/pages/docs/concepts/recipes.md
Just a tiny nitpick!
Thanks for the mention 🙏
> Fix `cva` Typo

- pnpm-lock.yaml
- website/pages/docs/concepts/style-props.mdx
- website/pages/docs/customization/theme.mdx
- website/src/components/token-docs/keyframes.tsx
- website/src/components/token-docs/query.ts
- website/src/mdx/token-docs.tsx
> docs: add keyframes documentation

- website/pages/docs/getting-started/storybook.mdx
> docs: remove extra whitespace

- website/pages/docs/customization/theme.mdx
- website/src/components/token-docs/query.ts
- website/src/components/token-docs/sizings.tsx
- website/src/mdx/token-docs.tsx
> website: add sizes docs

- website/pages/docs/customization/conditions.mdx
- website/pages/docs/index.mdx
- Update playground link
- Fix typos
> docs: some fixes

- website/pages/docs/getting-started/nextjs.mdx
The code snippet refers to the file name for pages dir here. Quick fix!
> fix(docs): Fix typo in Next.js app dir Getting Started

- website/app/layout.tsx
- website/pages/_app.tsx
- website/styles/fonts.ts
> fix(website): duplicated font loader function

- website/pages/docs/theming/layer-styles.md
Replaced `textStyles` (`text-styles`) with `layerStyles` (`layer-styles`)
> fix: textStyles to layerStyles

- website/pages/docs/theming/tokens.md
Fixed some typos. Please review.
> docs: update tokens.md typos

- .changeset/cold-apricots-clap.md
- packages/cli/src/cli-main.ts
- packages/parser/__tests__/fixture.ts
- packages/parser/__tests__/svelte.test.ts
- packages/parser/__tests__/vue.test.ts
- packages/parser/package.json
- packages/parser/src/project.ts
- packages/parser/src/svelte-to-tsx.ts
- packages/parser/src/vue-to-tsx.ts
- playground/next.config.js
- pnpm-lock.yaml
- sandbox/nuxt/components/CompositionApiDemo.vue
- sandbox/nuxt/components/SetupDemo.vue
- sandbox/nuxt/nuxt.config.ts
- sandbox/nuxt/pages/index.tsx
- sandbox/nuxt/panda.config.ts
- sandbox/svelte/panda.config.ts
- sandbox/svelte/src/routes/+page.svelte
https://github.com/chakra-ui/panda/assets/47224540/ed20cd03-bcc8-40f1-9f98-e18b4de3abbf
https://github.com/chakra-ui/panda/assets/47224540/9b928fdb-5788-41a5-88f5-24778d51d215
> feat(parser): vue/svelte support

- website/pages/docs/customization/theme.mdx
> docs: fix typo

- website/src/components/sections/testimonials.tsx
update testimonial social profile account
> update testimonial social profile account

- packages/cli/src/cli-main.ts
Maybe the `updateNotifier` should run first.
> chore(cli): optimize updateNotifier

- website/pages/docs/getting-started/astro.mdx
- website/pages/docs/getting-started/cli.mdx
- website/pages/docs/getting-started/gatsby.mdx
- website/pages/docs/getting-started/nextjs.mdx
- website/pages/docs/getting-started/postcss.mdx
- website/pages/docs/getting-started/preact.mdx
- website/pages/docs/getting-started/qwik.mdx
- website/pages/docs/getting-started/redwood.mdx
- website/pages/docs/getting-started/remix.mdx
- website/pages/docs/getting-started/solidjs.mdx
- website/pages/docs/getting-started/storybook.mdx
- website/pages/docs/getting-started/svelte.mdx
- website/pages/docs/getting-started/vite.mdx
- website/pages/docs/getting-started/vue.mdx
add gitignore outdir note to docs
> docs: add gitignore outdir note

- website/pages/docs/concepts/conditional-styles.md
related https://github.com/chakra-ui/panda/discussions/912
> docs(condtions): arbitrary selectors + at rules

- .changeset/plenty-onions-search.md
- packages/cli/src/cli-main.ts
- packages/core/src/stylesheet.ts
- packages/logger/src/create-logger.ts
- packages/logger/src/index.ts
- packages/logger/src/utils.ts
- full stack trace when using PANDA_DEBUG
- specific CssSyntaxError to better spot the error
it helps debugging
no
> chore: provide better error logs

- website/pages/docs/guides/virtual-color.md
related https://github.com/chakra-ui/panda/discussions/890
> docs(virtual-color): usage with recipes + color mode

- .changeset/fresh-jeans-collect.md
- packages/generator/__tests__/generate-prop-types.test.ts
- packages/preset-base/src/utilities/transforms.ts
- packages/studio/styled-system/types/prop-type.d.ts
Closes https://github.com/chakra-ui/panda/issues/930
Add negative fraction values to `translateX` and `translateY` utilities
no
> feat(preset-base): translateXY negative fraction values

- .changeset/lemon-fans-act.md
- packages/preset-base/src/utilities/flex-and-grid.ts
- packages/studio/styled-system/css/css.mjs
> fix: grid rows typo

- website/pages/docs/getting-started/_meta.json
- website/pages/docs/getting-started/nuxt.mdx
Hi, I've been using panda css with nuxt recently.
It seems to work really well so I've added in a guide for it.
If it needs re-wording please let me know
> Docs: Added a guide for use with Nuxt

- website/pages/docs/theming/text-styles.md
> Update text-styles.md , add export

- .changeset/wild-jobs-develop.md
- packages/core/__tests__/static-css.test.ts
- packages/core/src/utility.ts
- packages/generator/src/artifacts/css/static-css.ts
Closes https://github.com/chakra-ui/panda/issues/963
the `getPropertyKeys` wasn't resolving all values
no
> fix(static-css): css rules

- .changeset/rotten-ants-type.md
- packages/cli/src/cli-main.ts
- packages/studio/styled-system/helpers.mjs
Closes https://github.com/chakra-ui/panda/issues/971
Fix CLI --config argument for cssgen/ship/analyze/debug commands
no
> fix(cli): configPath for cssgen/ship/analyze/debug

- packages/generator/src/artifacts/pkg-json.ts
Closes # 
- Adding `require` for all the exports within the artifact package json file regarding to this discussion  https://github.com/chakra-ui/panda/discussions/960
> Adding `require` for all exports in artifact package json file

- website/pages/docs/overview/faq.md
Closes # 
Broken links in the FAQ pages missing `/docs` prefix
404 on all relative links
They work xd
No
> fix(docs): FAQ broken links

- website/pages/docs/customization/utilities.mdx
Closes # 
I added an example how to use boolean values for utilities.
No
> docs(utilities): add example for boolean values

- website/pages/docs/concepts/conditional-styles.md
add customization link to conditions doc
> chore: add customization link to conditions doc

- playground/src/components/Preview/index.tsx
- playground/src/hooks/useResponsiveView.ts
- playground/theme/recipes/splitter.ts
Fixed issue where changing layout made responsive view weird
**Previous**
**Now**
> Playground responsive mode fix

- website/pages/docs/references/config.md
With this i try to make it clearer what strictTokens means.
> docs(config): describe strictTokens

- website/pages/docs/concepts/writing-styles.md
> Docs improvements - Writing Styles

- website/pages/docs/concepts/cascade-layers.md
> small grammatical change

- website/pages/docs/references/config.md
fix `jsxFramework` description
> chore: fix `jsxFramework` description

- .changeset/gold-maps-drop.md
- packages/generator/src/artifacts/css/flat-css.ts
- packages/types/package.json
- packages/types/src/hooks.ts
- pnpm-lock.yaml
Add a hook call when the final `styles.css` content has been generated, remove cyclic (from an unused hook) dependency
no
also remove an unused hook and its dependency
> feat(hooks): generator:css on the final styles.css

- website/pages/docs/installation/qwik.mdx
> docs: update qwik guide

- website/pages/docs/concepts/conditional-styles.md
Closes # 
I was reading "Conditional Styles" page at "Concept" section in documentation, and found some typos.
Minor typo in concepts/conditional-styles page
Will fix the typo
No
> Minor typo fix in concepts/conditional-styles page

- CHANGELOG.md
> changelog: Add new release

- playground/src/components/Toolbar.tsx
Show latest version in playground
> chore: show panda's version in playground

- .changeset/cyan-kids-cover.md
- packages/cli/package.json
- packages/cli/src/cli-init.ts
- packages/cli/src/cli-main.ts
- pnpm-lock.yaml
> refactor(cli): interactive mode with clack

- .changeset/empty-eyes-knock.md
- packages/cli/src/index.ts
Add a `defineUtility` method to `@pandacss/dev`
> feat: add `defineUtility` method

- website/pages/docs/concepts/responsive-design.md
Closes #1250
Document array syntax for responsive styling
> Document array syntax for responsive styling

- CHANGELOG.md
- website/pages/docs/references/cli.md
> chore: add changelog for v0.12.0

- CHANGELOG.md
- website/pages/docs/concepts/writing-styles.md
> Add Changelog for v0.12.2

- CHANGELOG.md
> changelog: add v0.13.0

- .changeset/rare-cycles-enjoy.md
- packages/config/src/find-config.ts
- packages/error/src/index.ts
Allow `.mts` and `.cts` panda config extension
> Allow `.mts` and `.cts` panda config extension

- CHANGELOG.md
- website/pages/docs/concepts/writing-styles.md
> chore: add v0.13.1 changelog

- packages/cli/src/color-contrast-checker.d.ts
> fix: checkPairs returning type

- .changeset/mean-trees-kiss.md
- packages/generator/src/artifacts/js/conditions.ts
- packages/studio/styled-system/types/conditions.d.ts
adds the condition raw value in TS comment, pretty quick win
no
> types: add condition raw value in comment

- CHANGELOG.md
> Add changelog v0.14.0

- website/pages/docs/concepts/writing-styles.md
> fix: minor 'alignItems' typo

- CHANGELOG.md
- website/pages/docs/concepts/slot-recipes.md
- website/pages/docs/concepts/writing-styles.md
- website/pages/docs/installation/postcss.mdx
> Little update to docs

- CHANGELOG.md
- packages/generator/CHANGELOG.md
- website/pages/docs/concepts/writing-styles.md
> Little fixes in docs

- website/pages/docs/installation/nextjs.mdx
Update the docs to use correct file with `App Router`
> docs: use correct file css

- website/pages/docs/theming/layer-styles.md
Closes # 
Renamed 'text styles' to 'layer styles' in the layers styles section
No
> docs: corrected wrong style reference

- CHANGELOG.md
> Add v0.15.0 changelog

- website/pages/docs/concepts/slot-recipes.md
Updates the link in the docs to the new version of the `create-style-context.tsx` file from park-ui. There were some significant performance issues with the version that is currently linked. See: https://github.com/cschroeter/park-ui/issues/31
I have pointed the link at the main branch to allow for future updates/improvements to the file without needing another update to the docs. Happy to fix it to a commit though if that is preferred.
No
> docs: update link and label for create-style-context from park-ui

- CHANGELOG.md
> chore: add changelog v0.15.1

- website/pages/docs/guides/multiple-themes.md
fixes multiple themes `className` example
No new behavior
No
> docs: fix multiple themes example

- CHANGELOG.md
> chore: add v0.15.2 changelog

- CHANGELOG.md
> chore: add changelog for v0.15.3

- CHANGELOG.md
> chore: add changelog v0.15.4

- .draft/panda-debug.mdx
- .draft/token-studio.mdx
- website/pages/docs/concepts/style-props.mdx
- website/pages/docs/customization/conditions.mdx
- website/pages/docs/customization/patterns.mdx
- website/pages/docs/customization/utilities.mdx
- website/pages/docs/installation/astro.mdx
- website/pages/docs/installation/cli.mdx
- website/pages/docs/installation/nextjs.mdx
- website/pages/docs/installation/nuxt.mdx
- website/pages/docs/installation/postcss.mdx
- website/pages/docs/installation/qwik.mdx
- website/pages/docs/installation/remix.mdx
- website/pages/docs/installation/solidjs.mdx
- website/pages/docs/installation/storybook.mdx
- website/pages/docs/installation/svelte.mdx
- website/pages/docs/installation/vite.mdx
- website/pages/docs/installation/vue.mdx
Closes #1460
> Adds bun documentation to the panda css documentation
- currently the docs only support npm, yarn, pnpm
- new support includes bun in the docs so: npm, yarn, pnpm, bun where applicable 
No
> docs: added bun to the documentation

- .gitignore
- CHANGELOG.md
> chore: add changelog v0.15.5

- website/pages/docs/concepts/writing-styles.md
Fix props value
Maybe undefined
Pass children correctly 
No
None
> 🐛 Fix props of writing-styles.md

- CHANGELOG.md
> chore: Add changelog v0.16.0

- CONTRIBUTING.md
- README.md
adapted the chakra-ui guide for Panda
> docs: CONTRIBUTING.md

- CHANGELOG.md
> chore: changelog v0.17.0

- .changeset/few-ducks-press.md
- packages/cli/src/cli-main.ts
- packages/cli/src/types.ts
- packages/studio/scripts/studio.ts
> feat(studio): add support for host and port flags

- CHANGELOG.md
> chore: changelog 0.17.1

- CHANGELOG.md
> chore: changelog 0.17.2

- .changeset/smart-kings-marry.md
- packages/node/src/builder.ts
- packages/node/src/node-runtime.ts
- packages/node/src/setup-config.ts
> fix(studio): update fs-extra imports

- CHANGELOG.md
> chore: add changelog 0.17.3

- CHANGELOG.md
> chore: add changelog 0.17.4

- .changeset/fresh-monkeys-smash.md
- packages/studio/src/components/semantic-color.tsx
- packages/studio/src/components/typography-playground.tsx
- packages/studio/src/lib/panda.context.ts
- packages/studio/styled-system/chunks/src__components__color-wrapper.css
- packages/studio/styled-system/chunks/src__components__colors.css
- packages/studio/styled-system/chunks/src__components__empty-state.css
- packages/studio/styled-system/chunks/src__components__font-family.css
- packages/studio/styled-system/chunks/src__components__font-tokens.css
- packages/studio/styled-system/chunks/src__components__input.css
- packages/studio/styled-system/chunks/src__components__layer-styles.css
- packages/studio/styled-system/chunks/src__components__nav-item.css
- packages/studio/styled-system/chunks/src__components__overview.css
- packages/studio/styled-system/chunks/src__components__radii.css
- packages/studio/styled-system/chunks/src__components__semantic-color.css
- packages/studio/styled-system/chunks/src__components__side-nav-item.css
- packages/studio/styled-system/chunks/src__components__side-nav.css
- packages/studio/styled-system/chunks/src__components__text-styles.css
- packages/studio/styled-system/chunks/src__components__theme-toggle.css
- packages/studio/styled-system/chunks/src__components__token-content.css
- packages/studio/styled-system/chunks/src__components__token-group.css
- packages/studio/styled-system/chunks/src__components__typography-playground.css
- packages/studio/styled-system/chunks/src__layouts__Sidebar.css
- packages/studio/styled-system/styles.css
Fix issue where error is thrown for semantic tokens with raw values
> Fix studio semantic colors

- .changeset/many-readers-join.md
- packages/core/src/serialize.ts
- packages/parser/__tests__/output.test.ts
wip: failing test with array syntax usage within recipes
> fix: array syntax in config recipe

- CHANGELOG.md
> chore: changelog 0.17.5

- .changeset/modern-gorillas-promise.md
- packages/cli/src/cli-init.ts
- packages/cli/src/cli-main.ts
Add `--strict-tokens` flag and question in the interactive CLI
> feat(cli): add --strict-tokens flag & question in interactive CLI

- website/pages/docs/references/cli.md
> chore: update cli references

- .changeset/six-radios-shave.md
- packages/cli/src/cli-init.ts
- packages/node/package.json
- packages/node/src/setup-config.ts
- pnpm-lock.yaml
Fix CLI interactive mode `syntax` question values and prettify the generated `panda.config.ts` file
> fix(cli): -i syntax option and prettify output

- .changeset/slimy-bikes-return.md
- packages/generator/__tests__/generate-token.test.ts
- packages/token-dictionary/__tests__/docs.test.ts
- packages/token-dictionary/__tests__/tokens.test.ts
- packages/token-dictionary/__tests__/transform-border.test.ts
- packages/token-dictionary/src/dictionary.ts
- packages/token-dictionary/src/is-composite.ts
- packages/token-dictionary/src/token.ts
- packages/token-dictionary/src/transform.ts
Closes https://github.com/chakra-ui/panda/issues/1638
Fix issue with incorrect css emitted for composite tokens
> fix: shadow semantic token

- CHANGELOG.md
> chore: add changelog 0.18.1

- CHANGELOG.md
> chore: changelog 0.18.2

- CHANGELOG.md
> Add changelog v0.18.3

- website/pages/docs/concepts/slot-recipes.md
In slot-recipe Compound Components example, Control should be wrapped with withContext not withProvider
> docs:fix slot-recipe example

- CHANGELOG.md
> changelog: 0.19.0

- website/pages/docs/concepts/patterns.md
- website/pages/docs/concepts/recipes.md
I fixed typo using class attribute in jsx in pages of patterns and recipes.
> docs: replace `class` to `className`

- playground/src/components/LayoutControl.tsx
- playground/src/components/Playground.tsx
- playground/src/components/Preview/BreakpointControl.tsx
- playground/src/components/Preview/index.tsx
- playground/src/components/icons.tsx
- playground/src/hooks/usePanda.ts
- playground/src/hooks/useResponsiveView.ts
Add responsive breakpoints to playground
> Add responsive breakpoints to playground

- website/pages/docs/concepts/writing-styles.md
- website/pages/docs/utilities/_meta.json
- website/pages/docs/utilities/background.md
- website/pages/docs/utilities/border.md
- website/pages/docs/utilities/divide.md
- website/pages/docs/utilities/effects.md
> docs: update utilities

- .changeset/wicked-forks-drive.md
- packages/cli/src/cli-main.ts
- packages/cli/src/types.ts
Add a --watch flag to the `panda ship` command
no
> feat(cli): panda ship --watch flag

- website/pages/docs/utilities/flex-and-grid.md
Just read the docs and found this "typo"
> docs: fixed typo

- playground/src/hooks/usePlayground.ts
Track pristine state in playground
> Track pristine state in playground

- playground/src/hooks/usePlayground.ts
> Fix playground diff state

- playground/src/hooks/usePlayground.ts
> Fix pristine state

- CHANGELOG.md
> Changelog v0.21.0

- website/pages/docs/references/config.md
I think this should be `"hash": true` instead of false right?
Otherwise just close 😇
Closes # 
> docs: fix hash example in config.md

- playground/src/hooks/useEditor.ts
Add wordwrap to playground editor
> Add wordwrap to playground editor

- .changeset/khaki-socks-give.md
- packages/preset-open-props/__tests__/borders.test.ts
- packages/preset-open-props/__tests__/keyframes.test.ts
- packages/preset-open-props/src/borders.ts
- packages/preset-open-props/src/keyframes.ts
Fix conditonal varaibles in border radii
> Open props: Fix conditonal varaibles in border radii

- website/pages/docs/concepts/patterns.md
Closes # 
Fix small typo - missing "that"
n/a
n/a
No
n/a
> fix: typo in Patterns documentation

- CHANGELOG.md
> Add changelog: v0.22.0

- CHANGELOG.md
> Add changelog v0.22.1

- website/pages/docs/installation/postcss.mdx
Fix some spelling typos in the docs
> Nothing
> Nothing
No
> docs: fix typos

- playground/package.json
- playground/src/components/Playground.tsx
- playground/src/dts/@pandacss_types.d.ts
- playground/src/dts/react.d.ts
- playground/src/hooks/useEditor.ts
- playground/src/lib/auto-import.ts
- pnpm-lock.yaml
Add auto import to playground
https://github.com/chakra-ui/panda/assets/30869823/e3819751-3aa8-4e0c-ae5d-c5876eaa5d3f
> Add auto import to playground

- playground/src/lib/auto-import.ts
Add jsx helpers to auto imports
> Add jsx helpers to auto imports

- website/pages/docs/concepts/writing-styles.md
Remove redundant numeric warning
> Remove redundant numeric warning

- .changeset/lovely-rings-fix.md
- packages/core/src/layers.ts
- packages/node/src/builder.ts
- packages/node/src/debug-files.ts
Fix performance issues where the process could get slower due to postcss rules held in memory.
Closes #1849
> fix: improve HMR and reduce memory usage

- .changeset/tall-dryers-travel.md
- packages/logger/src/format-entry.ts
Log stacktrace on error instead of only logging the message
> fix(error): log trace instead of only the message

- CHANGELOG.md
> Add changelog v0.23.0

- playground/src/components/Playground.tsx
- playground/src/hooks/useEditor.ts
- playground/src/lib/auto-import.ts
> Cleanup libs in playground lifecycle

- playground/src/hooks/useEditor.ts
Playground wordwrap state in localstorage
> Playground wordwrap state in localstorage

- playground/src/components/Editor.tsx
- playground/src/components/GeneratedCss.tsx
Playground: fix default wordwrap bug
> Playground: fix default wordwrap bug

- CHANGELOG.md
> Add Changelog v0.24.0

- playground/src/hooks/usePanda.ts
there was a slight regression after the 0.24 release on the playground
> playground: add static-css tab and generation

- playground/src/hooks/useConfig.ts
- playground/src/lib/config/eval-config.ts
Playground: fix playgrounds with error config
> Playground: fix playgrounds with error config

- CHANGELOG.md
> Add changelog v0.24.1

- playground/src/components/Preview/index.tsx
- playground/src/components/Toolbar.tsx
Add index link to reset playground
> Add index link to reset playground

- website/src/components/feature-marquee.tsx
partially fixes https://github.com/chakra-ui/panda/issues/1908 as this PR only takes care of the specific issue mentionned
> fix(a11y): prevent landing animation on prefer-reduced-motion enabled

- playground/src/hooks/usePandaContext.ts
- playground/src/lib/config/resolve-config.ts
Playground: fix eject behaviour
> playground: fix eject behaviour

- CONTRIBUTING.md
Small docs typo 🙂 great contributing guide otherwise!
> docs: fix followin(g) typo in CONTRIBUTING.md

- playground/package.json
- playground/src/lib/config/eval-config.ts
- pnpm-lock.yaml
Playground: parse typescript in config
> playground: parse typescript in config

- CHANGELOG.md
> Changelog v0.24.2

- website/pages/docs/overview/faq.md
Docs: FAQ for overriding other libraries
> Docs: FAQ for overriding other libraries

- CHANGELOG.md
> Add changelog v0.25.0

- website/pages/docs/customization/patterns.mdx
> Document strict patterns

- .changeset/gentle-jars-draw.md
- packages/shared/__tests__/arbitrary-value.test.ts
- packages/shared/src/arbitrary-value.ts
Fix issue where `[]` escape hatch clashed with named grid lines
Closes #1950
> Fix escape hash clash

- .changeset/orange-monkeys-knock.md
- packages/types/src/config.ts
Remove eject type from presets
> Remove eject type from presets

- CHANGELOG.md
> Add changelog v0.26.0

- playground/src/components/PlaygroundContent.tsx
> Fix playground diff preview

- .changeset/large-deers-move.md
- packages/preset-base/src/conditions.ts
- packages/studio/styled-system/types/conditions.d.ts
> Fix `placeholder` condition in `preset-base`

- CHANGELOG.md
> Add changelog v0.26.2

- CHANGELOG.md
> Add changelog v0.27.0

- CHANGELOG.md
- playground/src/components/PlaygroundContent.tsx
- playground/src/components/Toolbar.tsx
- playground/src/hooks/useEditor.ts
> Add changelog v0.27.1

- CHANGELOG.md
> Add changelog v0.27.2

- pnpm-lock.yaml
- sandbox/remix/.eslintrc.cjs
- sandbox/remix/.eslintrc.js
- sandbox/remix/.gitignore
- sandbox/remix/README.md
- sandbox/remix/app/entry.server.tsx
- sandbox/remix/app/root.tsx
- sandbox/remix/app/routes/_index.tsx
- sandbox/remix/package.json
- sandbox/remix/postcss.config.cjs
- sandbox/remix/remix.config.js
- sandbox/remix/server.ts
- sandbox/remix/tsconfig.json
- website/pages/docs/installation/remix.mdx
> docs: update remix guide

- CHANGELOG.md
> Add changelog v0.27.3

- packages/core/__tests__/atomic-rule.test.ts
- packages/core/__tests__/recipe-nesting.test.ts
- packages/core/__tests__/rule-processor.test.ts
- packages/core/__tests__/sort-style-rules.test.ts
- packages/core/__tests__/static-css.test.ts
- packages/core/src/optimize.ts
- packages/core/src/style-encoder.ts
- packages/generator/__tests__/generate-token.test.ts
- packages/parser/__tests__/output.test.ts
follow up to https://github.com/chakra-ui/panda/pull/2035
> fix: sort media queries after the CSS generation step again

- website/pages/docs/concepts/merging-styles.md
> Fix typo: css -> css.raw

- .changeset/famous-news-search.md
- packages/studio/src/icons/logo.tsx
- packages/studio/src/layouts/Sidebar.astro
- packages/studio/styled-system/jsx/is-valid-prop.mjs
> Inject custom logo in studio

- CHANGELOG.md
> Add changelog v0.28.0

- playground/src/hooks/usePandaContext.ts
fix https://play.panda-css.com/UlCu972naX
> fix(playground): fallback to default config

- website/pages/docs/concepts/template-literals.md
Update template literal token docs
> Update template literal token docs

- CHANGELOG.md
> Add changelog v0.29.0

- CHANGELOG.md
> Add changelog v/0.29.1

- website/pages/docs/installation/astro.mdx
PR of the highest importance: correction of snippet indentation on the Astro documentation page 
don't thanks me 😎
> docs: fix Astro snippets indentation

- packages/postcss/__tests__/postcss.test.ts
- packages/postcss/__tests__/samples/panda.config.cjs
- packages/postcss/package.json
- packages/postcss/src/index.ts
- pnpm-lock.yaml
this PR adds some basic tests for the postcss plugin
i did this initially because i wanted to add a small feature to the plugin ( without breaking anything ). but i couldn't find a solution, see #2123
> test: add postcss tests

- CHANGELOG.md
- website/pages/docs/references/config.md
> Add changelog v0.30.0

- CHANGELOG.md
> Add changelog v0.30.1

- website/pages/docs/concepts/hooks.md
> docs: add more hook docs

- .github/FUNDING.yml
> chore: add funding

- website/pages/docs/concepts/hooks.md
> Fix grammar in hooks.md

- CHANGELOG.md
- website/pages/docs/concepts/hooks.md
> Add changelog 0.30.2

- CHANGELOG.md
Add changes for version 0.31.0
> Add changes for version 0.31.0

- package.json
- packages/extractor/package.json
- packages/node/package.json
- packages/parser/package.json
- playground/package.json
- pnpm-lock.yaml
https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/CHANGELOG.md#2100-2023-12-02
> chore: update ts-morph to v21.0.1 to match TS 5.3

- CHANGELOG.md
- website/pages/docs/references/config.md
> Add changelog v0.32.0

- website/pages/docs/theming/tokens.md
extend should go before tokens
Closes # 
Following the docs didn't work. We found out this was wrong in the docs.
no
> docs: update token extension

- .changeset/red-comics-itch.md
- packages/core/src/conditions.ts
- packages/generator/src/artifacts/css/token-css.ts
- packages/generator/src/artifacts/js/conditions.ts
Closes https://github.com/chakra-ui/panda/issues/2259
Fix conditions accessing `Cannot read properties of undefined (reading 'raw')`
> fix: conditions accessing

- website/pages/docs/guides/component-library.md
Closes https://github.com/chakra-ui/panda/discussions/2266
> docs: component library broken link & changes

- CHANGELOG.md
- website/pages/docs/customization/config-functions.md
> Add changelog v0.33.0

- playground/src/components/Examples/utils.ts
- playground/src/hooks/useEditor.ts
- playground/src/lib/format.ts
Fix config indent in playground
> Fix config indent in playground

- playground/src/hooks/usePandaContext.ts
- playground/src/lib/config/resolve-config.ts
> Fix hooks in playground

- website/pages/docs/installation/svelte.mdx
Closes # 
This is what the official SvelteKit scaffolding contains.
> Module '"@sveltejs/kit/vite"' has no exported member 'vitePreprocess'.ts(2305)
Works.
No.
> Docs: Installation: Update SvelteKit vitePreprocess import path

- CHANGELOG.md
> Add changelog v0.34.0

- CHANGELOG.md
> Add changelog v0.34.1

- packages/config/__tests__/validate-config.test.ts
- packages/config/src/validation/validate-tokens.ts
- packages/studio/CHANGELOG.md
follow-up to https://github.com/chakra-ui/panda/pull/2289 where I left a typo
makes token referencing path with DEFAULT not throw for the validation check
> fix: validation issue when referencing a token with DEFAULT

- playground/package.json
- playground/src/components/Examples/utils.ts
- playground/src/components/PlaygroundContent.tsx
- playground/src/components/Preview/index.tsx
- playground/src/hooks/usePanda.ts
- playground/src/hooks/usePandaContext.ts
- playground/src/hooks/usePlayground.ts
- playground/src/lib/config/resolve-config.ts
- pnpm-lock.yaml
> playground: add config validation

- CHANGELOG.md
> chore: add changelog v0.34.2

- packages/core/package.json
- pnpm-lock.yaml
1 less deps to install, doesn't change anything otherwise
> chore: rm autoprefixer dependency (already unused)

- .changeset/tasty-apples-pretend.md
> chore: update changeset

- CHANGELOG.md
> chore: add changelog v0.35.0

- packages/astro-plugin-studio/CHANGELOG.md
- packages/cli/CHANGELOG.md
- packages/config/CHANGELOG.md
- packages/core/CHANGELOG.md
- packages/extractor/CHANGELOG.md
- packages/fixture/CHANGELOG.md
- packages/generator/CHANGELOG.md
- packages/logger/CHANGELOG.md
- packages/node/CHANGELOG.md
- packages/parser/CHANGELOG.md
- packages/postcss/CHANGELOG.md
- packages/preset-base/CHANGELOG.md
- packages/preset-panda/CHANGELOG.md
- packages/shared/CHANGELOG.md
- packages/studio/CHANGELOG.md
- packages/token-dictionary/CHANGELOG.md
- packages/types/CHANGELOG.md
> chore: prettier fix

- packages/studio/src/components/semantic-color.tsx
~~Closes~~
- Relate to https://github.com/chakra-ui/panda/issues/2343
Fix this error.
<kbd> ![image](https://github.com/chakra-ui/panda/assets/13148112/b68ec4e9-d572-424e-a9a6-e6688627cc7f)
The error in the screenshot above is displayed.
Can now display screen without error.
No
> fix(studio): undefined error for semantic-color.tsx

- CHANGELOG.md
> chore: add changelog v0.36.0

- packages/astro-plugin-studio/CHANGELOG.md
- packages/cli/CHANGELOG.md
- packages/config/CHANGELOG.md
- packages/core/CHANGELOG.md
- packages/extractor/CHANGELOG.md
- packages/fixture/CHANGELOG.md
- packages/generator/CHANGELOG.md
- packages/is-valid-prop/CHANGELOG.md
- packages/logger/CHANGELOG.md
- packages/node/CHANGELOG.md
- packages/parser/CHANGELOG.md
- packages/postcss/CHANGELOG.md
- packages/preset-base/CHANGELOG.md
- packages/preset-panda/CHANGELOG.md
- packages/shared/CHANGELOG.md
- packages/studio/CHANGELOG.md
- packages/token-dictionary/CHANGELOG.md
- packages/types/CHANGELOG.md
> chore: prettier format

- CHANGELOG.md
- packages/astro-plugin-studio/CHANGELOG.md
- packages/cli/CHANGELOG.md
- packages/config/CHANGELOG.md
- packages/core/CHANGELOG.md
- packages/extractor/CHANGELOG.md
- packages/fixture/CHANGELOG.md
- packages/generator/CHANGELOG.md
- packages/is-valid-prop/CHANGELOG.md
- packages/logger/CHANGELOG.md
- packages/node/CHANGELOG.md
- packages/parser/CHANGELOG.md
- packages/postcss/CHANGELOG.md
- packages/preset-base/CHANGELOG.md
- packages/preset-panda/CHANGELOG.md
- packages/shared/CHANGELOG.md
- packages/studio/CHANGELOG.md
- packages/token-dictionary/CHANGELOG.md
- packages/types/CHANGELOG.md
> chore: add chnagelog

- CHANGELOG.md
- packages/astro-plugin-studio/CHANGELOG.md
- packages/cli/CHANGELOG.md
- packages/config/CHANGELOG.md
- packages/core/CHANGELOG.md
- packages/extractor/CHANGELOG.md
- packages/fixture/CHANGELOG.md
- packages/generator/CHANGELOG.md
- packages/is-valid-prop/CHANGELOG.md
- packages/logger/CHANGELOG.md
- packages/node/CHANGELOG.md
- packages/parser/CHANGELOG.md
- packages/postcss/CHANGELOG.md
- packages/preset-base/CHANGELOG.md
- packages/preset-panda/CHANGELOG.md
- packages/shared/CHANGELOG.md
- packages/studio/CHANGELOG.md
- packages/token-dictionary/CHANGELOG.md
- packages/types/CHANGELOG.md
> chore: add changelog v0.37.0

- CHANGELOG.md
- packages/astro-plugin-studio/CHANGELOG.md
- packages/cli/CHANGELOG.md
- packages/config/CHANGELOG.md
- packages/core/CHANGELOG.md
- packages/extractor/CHANGELOG.md
- packages/fixture/CHANGELOG.md
- packages/generator/CHANGELOG.md
- packages/is-valid-prop/CHANGELOG.md
- packages/logger/CHANGELOG.md
- packages/node/CHANGELOG.md
- packages/parser/CHANGELOG.md
- packages/postcss/CHANGELOG.md
- packages/preset-base/CHANGELOG.md
- packages/preset-panda/CHANGELOG.md
- packages/shared/CHANGELOG.md
- packages/studio/CHANGELOG.md
- packages/token-dictionary/CHANGELOG.md
- packages/types/CHANGELOG.md
> chore: add changelog v0.37.1

- website/pages/docs/installation/astro.mdx
> docs: Fix typo in Astro guide

- CHANGELOG.md
> chore: add changelog v0.38.0

- CHANGELOG.md
- packages/astro-plugin-studio/CHANGELOG.md
- packages/cli/CHANGELOG.md
- packages/config/CHANGELOG.md
- packages/core/CHANGELOG.md
- packages/extractor/CHANGELOG.md
- packages/generator/CHANGELOG.md
- packages/is-valid-prop/CHANGELOG.md
- packages/logger/CHANGELOG.md
- packages/node/CHANGELOG.md
- packages/parser/CHANGELOG.md
- packages/postcss/CHANGELOG.md
- packages/preset-base/CHANGELOG.md
- packages/preset-panda/CHANGELOG.md
- packages/shared/CHANGELOG.md
- packages/studio/CHANGELOG.md
- packages/token-dictionary/CHANGELOG.md
- packages/types/CHANGELOG.md
> chore: add changelog v0.39.0

- website/src/components/navbar.desktop.tsx
- website/src/components/navbar.mobile.tsx
Closes # 
The playground page is useful and helpful for users and developers who want to know about PandaCSS.
This adds a link to the playground page on the navigation.
No
> chore(website): add a link to playground on the navigation

- CHANGELOG.md
> Changelog v0.39.2

- CHANGELOG.md
> Changelog v0.40.0

- website/pages/docs/concepts/merging-styles.md
Closes # 
Documents merging sva + css styles. Similar to existing example for merging cva + css styles.
> docs: document merging sva + css styles

- website/pages/docs/guides/multiple-themes.md
Closes # 
Add `// panda.config.ts` to multiple-themes config docs
No
> docs: add config file location as comment

- CHANGELOG.md
> Changelog v0.41.0

- .changeset/famous-rockets-give.md
- packages/cli/src/cli-main.ts
- packages/cli/src/types.ts
- packages/extractor/src/box.ts
- packages/node/src/analyze-tokens.ts
- packages/node/src/classify.ts
- packages/parser/__tests__/ast-dynamic.test.ts
- packages/types/src/analyze-report.ts
Minor changes in the `panda analyze --output coverage.json` file
no
> refactor(cli): panda analyze minor changes

- website/pages/docs/concepts/_meta.json
- website/pages/docs/concepts/extend.md
- website/pages/docs/concepts/styled-system.mdx
> docs: update guides meta

- website/pages/docs/concepts/styled-system.mdx
docs: update styled system title
> docs: update styled system title

- CHANGELOG.md
> Changelog v0.42.0

- CHANGELOG.md
- website/pages/docs/guides/fonts.md
> Changelog v0.44.0

- website/pages/docs/references/cli.md
Closes # 
Hello there, I love this awesome lib! thanks to maintaining 👍 
btw, I found some typo at link
https://github.com/user-attachments/assets/0cb7851e-9cfc-4aa7-84bf-61e806ea6d06
does not located well
https://github.com/user-attachments/assets/f08e4e02-c949-4fd0-a02d-dbce1784d1c0
found id
no
> docs: typo update at cli importMap

- CHANGELOG.md
- website/pages/docs/guides/fonts.md
> Changelog v0.45.0

- website/pages/docs/customization/deprecations.md
> docs: add deprecation guide

- CHANGELOG.md
- website/pages/docs/customization/deprecations.md
> Add Changelog v0.45.1

- CHANGELOG.md
> Changelog v0.45.2

- website/pages/docs/concepts/hooks.md
Closes # 
Set the correct link to the sandbox snippet.
No
> docs: fix wrong sandbox link

- CHANGELOG.md
> chore: add changelog v0.46.0

- website/pages/docs/installation/_meta.json
- website/pages/docs/installation/angular.mdx
This PR adds a doc explaining how to integrate with the Angular CLI
No
> docs: add Angular docs

- CHANGELOG.md
> Changelog v0.46.1

- website/pages/docs/references/cli.md
Bring cli references up to date
> chore(docs): bring cli references up to date

- package.json
- playground/src/components/ArtifactsPanel.tsx
- playground/src/components/GeneratedCss.tsx
- pnpm-lock.yaml
- website/pages/docs/references/cli.md
Fix generated css formatting in playground
> fix(playground): generated css formatting

- CHANGELOG.md
- website/.eslintignore
- website/.eslintrc.cjs
- website/package.json
> Changelog v0.47.0

- website/pages/docs/concepts/recipes.md
Ran into an unncessary space as shown below. This PR fixes it.
The extra space cuases a type error.
No type error. It also works.
No
> docs: remove unncessary space

- website/pages/docs/concepts/merging-styles.md
- website/pages/docs/concepts/patterns.mdx
- website/pages/docs/concepts/template-literals.md
- website/pages/docs/guides/dynamic-styling.md
Fix some grammar and typo issues
> docs: fix some grammar and typo issues

- CHANGELOG.md
> Changelog v0.47.1

- CHANGELOG.md
> Changelog v0.48.0

- website/pages/docs/theming/tokens.md
> chore: add cursor token docs

- .changeset/friendly-knives-stare.md
- packages/core/__tests__/style-encoder.test.ts
- packages/node/src/build-info.ts
Closes #3001 
Add static css artifacts to build info
> fix: static css + build info

- CHANGELOG.md
> Changelog v0.49.0

- website/next-env.d.ts
- website/pages/docs/theming/_meta.json
- website/pages/docs/theming/animation-styles.md
> chore: add animation styles docs

- CHANGELOG.md
> Changelog v0.50.0

- CHANGELOG.md
> Changelog v0.51.0

- website/pages/docs/theming/usage.mdx
Closes # 
Layout shift is occurring due to indentation issues in the code blocks. To improve UX, removed the indentation.
https://github.com/user-attachments/assets/b7d89e12-9721-46b1-9323-db910df1e65b
I have modified the indentation within the code block (```).
No
> docs: remove unnecessary indent

- website/pages/docs/installation/storybook.mdx
- website/pages/docs/installation/svelte.mdx
Related #3094
* Add a troubleshooting section to the Storybook Getting Started page when using SvelteKit
> docs(svelte+storybook): add configuration when using storybook with sveltekit

- CHANGELOG.md
> Changelog v0.52.0

- CHANGELOG.md
> Changelog v0.53.2

- website/pages/docs/migration/styled-components.md
Closes # 
I fix the typo.
Thanks. 🙇‍♂️
> docs: fix the typo at styled-components

- CHANGELOG.md
> Changelog v0.53.5

- CHANGELOG.md
> Changelog v0.53.6

- CHANGELOG.md
> Changelog v0.53.7

- website/pages/docs/customization/utilities.mdx
Fixed a small typo found while reading the doc.
No
> docs(website): fix minor error in  utilities.mdx example

- CHANGELOG.md
> Changelog v1.0.1
